### ISSUE TITLE
White River Watch Revisited under-water bug

### ISSUE THREAD

**Issue by Soundtrack2chaos** [TitansBane/Elysium#1]
Idk how to describe this, so I recorded it. On the bottom floor of the Watch, I went by the wall and all of a sudden I was underwater and started swimming. Here is the video: https://youtu.be/I2096__UUNk

**Comment by TitansBane** [comment]
A bug that is present in White River Watch - Revisited mod which I can fix by forwarding the new changes to the CRP.
