### ISSUE TITLE
Failed download Dyndolod 3D Output (Creation Club)

### ISSUE THREAD

**Issue by GamerLadyJules** [TitansBane/Elysium#100]
Following mod fails and will not resolve/no solution.
- Elysium - Dyndolod 3D Output (Creation Club).7z

Have the latest Elysium modlist downloaded.

Log:

8.72 - Configuring Processor
8.73 - Install Folder: G:\Gaming\Skyrim SE\Wabbajack\install
8.73 - Downloads Folder: G:\Gaming\Skyrim SE\Wabbajack\install\downloads
8.73 - Game Folder: E:\SteamLibrary\steamapps\common\Skyrim Special Edition
8.73 - Wabbajack Folder: G:\Gaming\Skyrim SE\Wabbajack
8.73 - Drive watcher is starting. Will warn at 8GB and error at 4GB
8.73 - Starting Drive watcher on G:\ currently 403.5GB free out of 931.5GB
8.73 - Starting Drive watcher on E:\ currently 425.6GB free out of 465.8GB
8.73 - Validating Game ESMs
8.74 - Creating Output Folders
8.82 - Optimizing ModList
8.82 - Optimizing ModList directives
10.24 - Looking for files to delete
10.26 - Cleaning empty folders
10.87 - Looking for unmodified files
11.25 - Updating ModList
11.26 - Optimized 150995 directives to 150995 required
11.3 - Hashing Archives
11.3 - Looking for files to hash
12.38 - Found 18531 total files, 1770 matching filesize
12.72 - Downloading Missing Archives
12.72 - Missing 15 archives
12.72 - Getting Nexus API Key, if a browser appears, please accept
13.38 - Logged into the nexus as ScenicGaming
13.38 - Nexus calls remaining: 2500 daily, 100 hourly
13.51 - Logged into the nexus as ScenicGaming
13.51 - Nexus calls remaining: 2500 daily, 100 hourly
13.51 - Loading server whitelist
15.43 - Loaded permissions for 440 servers and 174 Google Drive files
15.43 - File hash check (-42) c13acd70b9c4fb3a03fb4d86bfe1288e97a4e9987fba381c75664ac6eea52e0d
15.48 - Downloading Pandorable's Lethal Ladies - Salt and Wind-44975-1-0-1612701004.zip
15.48 - Downloading SC - KS Hairdos Retextured-38820-1-8-1621881743.7z
15.49 - Downloading Metalsabers Beautiful Orcs - Salt and Wind-44975-1-0-1612429152.zip
16.04 - File hash check (-42) c13acd70b9c4fb3a03fb4d86bfe1288e97a4e9987fba381c75664ac6eea52e0d
16.63 - File hash check (-42) c13acd70b9c4fb3a03fb4d86bfe1288e97a4e9987fba381c75664ac6eea52e0d
17.26 - File hash check (-42) c13acd70b9c4fb3a03fb4d86bfe1288e97a4e9987fba381c75664ac6eea52e0d
21.16 - Downloading Elysium - Texgen Output.7z
92.72 - Downloading Project Clarity AIO Half Res Loose-45306-2-0-1614625586.7z
95.61 - Downloading Grass Cache Generated Files (Creation Club).7z
626.44 - Downloading Synthesis.zip
1203.66 - Downloading KS Hairdos SSE-6817-1-8-1621841731.7z
1684.33 - Downloading Know Your Enemy-13807-8-1-3-1621726938.rar
1687.77 - Downloading Elysium - Core Files.7z
1805.56 - Downloading Khajiit Caravan Mules-49058-1-2-1621768101.rar
1815.22 - Downloading Immersive Interactions-47670-1-24-1621697787.zip
1818.57 - Downloading Elysium - Dyndolod 3D Output (Creation Club).7z
3383.92 - Trying to find solution to broken download for Elysium - Dyndolod 3D Output (Creation Club).7z
3383.92 - Looking for generic upgrade for url9MezXa40= (-8256268082411095622)
3384.2 - No solution for broken download Elysium - Dyndolod 3D Output (Creation Club).7z WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/Elysium - Dyndolod 3D Output (Creation Club).7z_fa41a446-eec9-44f4-bb6d-e0e77f68de07 could be found
3384.2 - Downloading Elysium - Dyndolod 3D Output.7z
4916.31 - Downloading Animated Armoury - WACCF Patch-47213-2-2-2-1620939712.zip
10838.69 - Hashing Remaining Archives
10838.69 - Looking for files to hash
10840.33 - Found 18546 total files, 1785 matching filesize
10976.36 - Unable to download Elysium - Dyndolod 3D Output (Creation Club).7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/Elysium - Dyndolod 3D Output (Creation Club).7z_fa41a446-eec9-44f4-bb6d-e0e77f68de07)
10976.36 - Cannot continue, was unable to download one or more archives
10976.38 - File hash check (-42) c13acd70b9c4fb3a03fb4d86bfe1288e97a4e9987fba381c75664ac6eea52e0d
10976.38 - Vacuuming databases
10976.41 - Vacuuming completed
10976.63 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 69
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 156
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 373
10976.73 - File hash check (-42) c13acd70b9c4fb3a03fb4d86bfe1288e97a4e9987fba381c75664ac6eea52e0d

Second Log after failed installation and restart:

0.22 - Wabbajack Build - d3a28ee00bff1f4f1986acfdec6a12b7a324e686
0.23 - Running in G:\Gaming\Skyrim SE\Wabbajack
0.24 - Detected Windows Version: 10.0.19043.0
0.24 - System settings - (31.8GB RAM) (4.8GB Page), Display: 3840 x 2160 (10.8GB VRAM - VideoMemorySizeMb=10240)
0.24 - Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance.
0.24 - Outside of standard install folder, not updating
0.24 - Steam Library found at E:\SteamLibrary\steamapps
0.24 - Total number of Steam Libraries found: 1
0.24 - Searching for Steam Games in E:\SteamLibrary\steamapps
0.27 - Steam Game "Dwarf Shop" (1247640) is not supported, skipping
0.27 - Steam Game "The Infected" (1360000) is not supported, skipping
0.27 - Steam Game "Kenshi" (233860) is not supported, skipping
0.27 - Found Steam Game: "The Elder Scrolls V: Skyrim Special Edition" (489830) at E:\SteamLibrary\steamapps\common\Skyrim Special Edition
0.28 - Found Steam Workshop item file E:\SteamLibrary\steamapps\workshop\appworkshop_489830.acf for "The Elder Scrolls V: Skyrim Special Edition"
0.28 - Steam Game "Graveyard Keeper" (599140) is not supported, skipping
0.28 - Steam Game "Valheim" (892970) is not supported, skipping
0.28 - Steam Game "Valheim Dedicated Server" (896660) is not supported, skipping
0.28 - Searching for Steam Games in c:\program files (x86)\steam\steamapps
0.28 - Steam Game "Steamworks Common Redistributables" (228980) is not supported, skipping
0.28 - Total number of Steam Games found: 1
0.28 - Wabbajack.Common.StoreHandlers.StoreException: Could not open the GOG registry key!
0.28 - Wabbajack.Common.StoreHandlers.StoreException: Could not Init the GOGHandler, check previous error messages!
0.28 - Wabbajack.Common.StoreHandlers.StoreException: The GamesFolder for BethNet at C:\Program Files (x86)\Bethesda.net Launcher\games does not exist!
0.28 - Wabbajack.Common.StoreHandlers.StoreException: Could not load all Games from the BethNetHandler, check previous error messages!
0.28 - Epic Game Store is not installed
0.28 - Wabbajack.Common.StoreHandlers.StoreException: Could not load all Games from the EpicGameStoreHandler, check previous error messages!
0.29 - Found MFSTs from Origin: 
0.52 - Wabbajack Version: 2.4.4.2
0.53 - Configuring with SSL None
0.91 - Build server is alive
0.91 - File hash check (-42) c13acd70b9c4fb3a03fb4d86bfe1288e97a4e9987fba381c75664ac6eea52e0d
0.92 - Build server is alive
0.92 - File hash check (-42) c13acd70b9c4fb3a03fb4d86bfe1288e97a4e9987fba381c75664ac6eea52e0d
15.29 - Starting to install Elysium
15.29 - Cleaning VFS, this may take a bit of time
15.32 - Starting Installer Task
15.32 - Installation has Started
15.32 - File hash check (-42) c13acd70b9c4fb3a03fb4d86bfe1288e97a4e9987fba381c75664ac6eea52e0d
15.54 - Configuring Processor
15.55 - Install Folder: G:\Gaming\Skyrim SE\Wabbajack\install
15.55 - Downloads Folder: G:\Gaming\Skyrim SE\Wabbajack\install\downloads
15.55 - Game Folder: E:\SteamLibrary\steamapps\common\Skyrim Special Edition
15.55 - Wabbajack Folder: G:\Gaming\Skyrim SE\Wabbajack
15.55 - Drive watcher is starting. Will warn at 8GB and error at 4GB
15.55 - Starting Drive watcher on G:\ currently 382.6GB free out of 931.5GB
15.55 - Starting Drive watcher on E:\ currently 425.6GB free out of 465.8GB
15.55 - Validating Game ESMs
15.56 - Creating Output Folders
16.18 - Optimizing ModList
16.18 - Optimizing ModList directives
17.61 - Looking for files to delete
17.68 - Cleaning empty folders
18.25 - Looking for unmodified files
18.65 - Updating ModList
18.65 - Optimized 150995 directives to 150995 required
18.69 - Hashing Archives
18.69 - Looking for files to hash
19.76 - Found 18546 total files, 1785 matching filesize
134.64 - Downloading Missing Archives
134.64 - Missing 1 archives
134.64 - Getting Nexus API Key, if a browser appears, please accept
134.64 - Loading server whitelist
134.87 - Loaded permissions for 440 servers and 174 Google Drive files
134.87 - File hash check (-42) c13acd70b9c4fb3a03fb4d86bfe1288e97a4e9987fba381c75664ac6eea52e0d
134.95 - Downloading Elysium - Dyndolod 3D Output (Creation Club).7z
1649.26 - Trying to find solution to broken download for Elysium - Dyndolod 3D Output (Creation Club).7z
1649.26 - Looking for generic upgrade for url9MezXa40= (-8256268082411095622)
1649.48 - No solution for broken download Elysium - Dyndolod 3D Output (Creation Club).7z WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/Elysium - Dyndolod 3D Output (Creation Club).7z_fa41a446-eec9-44f4-bb6d-e0e77f68de07 could be found
1650.05 - Hashing Remaining Archives
1650.05 - Looking for files to hash
1651.33 - Found 18546 total files, 1785 matching filesize
1678.95 - Unable to download Elysium - Dyndolod 3D Output (Creation Club).7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/Elysium - Dyndolod 3D Output (Creation Club).7z_fa41a446-eec9-44f4-bb6d-e0e77f68de07)
1678.95 - Cannot continue, was unable to download one or more archives
1678.95 - File hash check (-42) c13acd70b9c4fb3a03fb4d86bfe1288e97a4e9987fba381c75664ac6eea52e0d
1678.95 - Vacuuming databases
1678.96 - Vacuuming completed
1678.97 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 69
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 156
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 373
1679.71 - File hash check (-42) c13acd70b9c4fb3a03fb4d86bfe1288e97a4e9987fba381c75664ac6eea52e0d

**Comment by GamerLadyJules** [comment]
Tried one more time and this time it worked, not sure why it failed the last few attempts.

**Comment by danielcor** [comment]
Having the very same issue...
