### ISSUE TITLE
What movement mods can be disabled?

### ISSUE THREAD

**Issue by Hazzens** [TitansBane/Elysium#102]
Hey folks, not sure if its my pc or the settings but I find the movement is very strange. When I tap W its super responsive, the camera and charachter overly lurge forward. Its the camera moving with it, its very strange. I downloaded this pack because it said it was mainly graphical updates, dont want anything but graphics so wondering if I can disable the movement mod?

**Comment by TitansBane** [comment]
You can't disable the behavior movement mod without having to rerun Nemesis. So I do not recommend it unless you know what you are doing.
