### ISSUE TITLE
Disk Space Warning Suggestion

### ISSUE THREAD

**Issue by edsaperia** [TitansBane/Elysium#107]
Hello!

A small suggestion: I ran out of disk space doing the downloads. It might be helpful to add a line to the installation instructions, something like "Ensure that you have 240GB of free space for the installation", or however much is required.

Many thanks for your great work!

**Comment by TekFolf** [comment]
If this system was added, I'm getting multiple disk warnings for the wrong drive. Not the drive wabbajack is residing on.
