### ISSUE TITLE
Widescreen fix for SkyUI isn't working

### ISSUE THREAD

**Issue by kxkxrxtx** [TitansBane/Elysium#112]
Like the title suggests, I have a 21:9 screen and I downloaded the extra plugins to addapt to my resolutions. I put the mod below SkyUI, change the plugin under _SkyUI_SE.esp_ (so _widescreen_skyui_fix.esp_ priority changes to 15), start the game, and when I go to items and magic menus the screen is cut from above and below on my screen. Don't know what I'm doing wrong : /

**Comment by Snowpup** [comment]
> Like the title suggests, I have a 21:9 screen and I downloaded the extra plugins to addapt to my resolutions. I put the mod below SkyUI, change the plugin under _SkyUI_SE.esp_ (so _widescreen_skyui_fix.esp_ priority changes to 15), start the game, and when I go to items and magic menus the screen is cut from above and below on my screen. Don't know what I'm doing wrong : /

For what it's worth I've gone ahead and made a patch for ultrawide and notified the creator of the "Complete Widescreen Fix" of the need for a full configurable patch for this mod.

My temporary patch can be found here:
https://www.nexusmods.com/skyrimspecialedition/mods/54854

You aren't doing anything wrong, it was just a missed problem and the "Complete Widescreen Fix" author wasn't aware of this mod. It's no big deal, it happens, but that patch above should fix you up if you're still attempting or interested in playing Elysium in widescreen.
