### ISSUE TITLE
Please Add "No More Absorb Swirl Effect" mod to documentation or to the mod package.

### ISSUE THREAD

**Issue by lconover** [TitansBane/Elysium#118]
Some NPCs are showing a swirl effect that is always present by them.  (One example NPC is in Dragonsreach near where the Jarl's throne is located. Unfortunately, I forgot to get her information!)  

Please consider adding mod ID 32269 to resolve it.  While it has a trade off of no longer seeing NPCs absorbing spell effects, the constant swirls on NPCs is also fairly awkward.)   Or, recommend that mod as part of your documentation for setup and allow the user to decide which they prefer.  Hopefully this will save some other user some time on researching "Why do random NPCs have a blue swirling vortex on them?"   

Thanks again for the fabulous mod pack.

**Comment by TitansBane** [comment]
This should be fixed now in the latest version.
