### ISSUE TITLE
LivingSkyrim3 (Problem with download)

### ISSUE THREAD

**Issue by Eblis99** [TitansBane/Elysium#125]
Error message:
113,57 - Encountered error, can't continue - System.Exception: File HTTPDownloader+State|https://storage.vectorplexus.com
|https://storage.vectorplexus.com/downloads/monthly_2020_09/High_Poly_Head_v1.4_(SE)_zip.85a520545cc9364ec7561e4bcfed8e75 failed validation

thanks in advance!

/S

**Comment by TitansBane** [comment]
This isn't Living Skyrim 3. Go here for reporting issues regarding LS3. https://github.com/ForgottenGlory/Living-Skyrim-3/issues
