### ISSUE TITLE
Issues with Elysium

### ISSUE THREAD

**Issue by WizDuck** [TitansBane/Elysium#132]
> 29.85 - Found 1373 total files, 1346 matching filesize
29.98 - Unable to download Miscellaneous Quests...as Miscellaneous Quests-11626-1-0.zip (NexusDownloader+State|SkyrimSpecialEdition|11626|31757)
29.98 - Unable to download Quest Conflict Fixes-12412-1-2-1617905127.zip (NexusDownloader+State|SkyrimSpecialEdition|12412|196916)
29.98 - Unable to download Random Encounter Tweaks-16804-1-1-1564773772.zip (NexusDownloader+State|SkyrimSpecialEdition|16804|101629)
29.98 - Unable to download The Notice Board Redefined 2K (Performance)-43257-1-0-1-1608146985.rar (NexusDownloader+State|SkyrimSpecialEdition|43257|174753)
29.98 - Cannot continue, was unable to download one or more archives

Can't join the discord, keeps saying invalid discord, made multiple accounts and same issue. Never used it before.

Can't manually download these either. Help

**Comment by Vince-Nieuw** [comment]
I had the exact same issue. Just hold on a bit until the modlist is updated.
The modlist should already display 'under maintenance' on the Wabbajack client, so it's work in progress.
