### ISSUE TITLE
Starting Elysium Instant Crash

### ISSUE THREAD

**Issue by NemoFish1** [TitansBane/Elysium#135]
Hi, Just downloaded the newest update and I am having problems where when I run SKSE it starts and then instantly crashes with the message "Mod Organizer is locked while the application is running. SkyrimSE.exe". It is definitely not running. I even checked task manager. I made sure to follow the instructions and uninstalled and reinstalled both the game and the mod list with the same result. Any suggestions? Thank you!

Edit: I deselected all the mods in Elysium and tried running SKSE through MO2 and it ran just fine so I am thinking it must be something in the mod list. I will keep trying things

Edit: It is the .NET Script Framework that is causing it to crash. I am looking into why now.

**Comment by TitansBane** [comment]
If you have something like Webroot or any other anti-virus protection it will block .NET Script Framework from working and you'll end up CTD'ing on startup.
