### ISSUE TITLE
Spell menu widescreen fix?

### ISSUE THREAD

**Issue by SyntexToxy** [TitansBane/Elysium#137]
Greetings and apologies for perhaps wasting yah time. I'm wondering has anyone reported that the spell menu still dosn't show properly even with the widescreen fixes applied? For me it cuts of the top part, not being able to see the spell/effect categories. I've applied the fixes just as you listed in the readme.

**Comment by TitansBane** [comment]
Hide the magicmenu.swf file in the Forget Spell mod. I need to update the widescreen fixes section in the Readme soon, though.

**Comment by Snowpup** [comment]
For what it's worth I've gone ahead and made a patch for 2560x1080 and notified the creator of the "Complete Widescreen Fix" of the need for a full configurable patch for this mod.

My temporary patch can be found here:
https://www.nexusmods.com/skyrimspecialedition/mods/54854

**Comment by TitansBane** [comment]
I went ahead and updated the readme to include your widescreen fix.

**Comment by Snowpup** [comment]
Hey that's awesome, thanks! I'll poke you if the author of the mega-list of Widescreen fixes incorporates it into his package for the sake of update and congruity. Mod pack is incredible btw, thanks for the effort and experience.

**Comment by Snowpup** [comment]
Sorry to pester you with another message but some users have tested it at 3440x1440 and said it worked well with that. If you could remove the 2560x1080 clarifier in the readme it might cull some confusion. I've done the same on the mod page as well. Thanks again!

> I went ahead and updated the readme to include your widescreen fix.
