### ISSUE TITLE
Dizzying movement / Passive swaying

### ISSUE THREAD

**Issue by MostDosed** [TitansBane/Elysium#141]
Hi,

Just installed today with no issues. However, in-game movement is extremely dizzying. It seems like the default movement is "sprinting" complete with that tunnel-vision effect, every time I move in any direction, even when not sprinting. This means it's constantly going from tunnel-vision to resting. Also, standing still has a constant swaying effect.

I'm sure these are related to a mod in the list - could you tell me which one, so I could look at removing or disabling via MCM?

**Comment by LunarDelta** [comment]
In the left-hand MO2 pane, search for "Improved Camera" and change the "Improved Camera" preset to the one without head bobbing.
