### ISSUE TITLE
Failed to download Dyndolod 3D Output (Creation Club).7z

### ISSUE THREAD

**Issue by jfranknichols** [TitansBane/Elysium#153]
I have tried about 6 times now. I have restart Wabbajack each time. I have twice rebooted my computer. Each time it downloads 5.4GB, but fails the has code test. I have a premium account on MEGA is that would help (is that where it is downloaded from?) If not, what suggestions?

0.24 - Wabbajack Build - 2b4227a2f9769cb4f02158b583dcba3f8d92759d
0.24 - Running in G:\WobbleDuckie\2.5.2.2
0.25 - Detected Windows Version: 10.0.19043.0
0.25 - System settings - (31.7GB RAM) (4.8GB Page), Display: 2560 x 1440 (11.6GB VRAM - VideoMemorySizeMb=10240)
0.25 - Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance.
0.27 - Getting new Wabbajack version list
0.27 - Steam: Found no Regex matches in Steam Config at g:/steam\config\config.vdf
0.27 - Steam: Found no path-matches in Library Folders file at g:/steam\steamapps\libraryfolders.vdf
0.27 - Steam: Found game Steamworks Common Redistributables (228980) at "g:/steam\steamapps\common\Steamworks Shared"
0.27 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "g:/steam\steamapps\common\Skyrim Special Edition"
0.28 - GOG: GOG was not found in the registry
0.28 - EGS: Unable to open Registry Key SOFTWARE\Epic Games\EOS
0.28 - Origin: LocalContent directory at C:\ProgramData\Origin\LocalContent does not exist
0.61 - Wabbajack Version: 2.5.2.2
0.82 - Build server is alive
0.82 - File hash check (-42) f81906cd0ae6fdfd3c28e4c2d9b7bbc57c0c64b8a4a7c8714afb3d41ab7ee613
0.99 - Build server is alive
0.99 - File hash check (-42) f81906cd0ae6fdfd3c28e4c2d9b7bbc57c0c64b8a4a7c8714afb3d41ab7ee613
2.26 - Loading ModLists from GitHub
21.68 - Starting to install Elysium
21.69 - Cleaning VFS, this may take a bit of time
21.75 - Starting Installer Task
21.75 - Installation has Started
21.75 - File hash check (-42) f81906cd0ae6fdfd3c28e4c2d9b7bbc57c0c64b8a4a7c8714afb3d41ab7ee613
21.92 - Configuring Processor
21.93 - Install Folder: G:\Elysium
21.94 - Downloads Folder: G:\Elysium\downloads
21.94 - Game Folder: g:\steam\steamapps\common\Skyrim Special Edition
21.94 - Wabbajack Folder: G:\WobbleDuckie\2.5.2.2
21.94 - Drive watcher is starting. Will warn at 8GB and error at 4GB
21.94 - Starting Drive watcher on G:\ currently 167.8GB free out of 465.5GB
21.94 - Starting Drive watcher on g:\ currently 167.8GB free out of 465.5GB
21.95 - Validating Game ESMs
21.96 - Creating Output Folders
22.67 - Optimizing ModList
22.68 - Optimizing ModList directives
25.44 - Looking for files to delete
25.5 - Cleaning empty folders
26.55 - Looking for unmodified files
27.15 - Updating ModList
27.15 - Optimized 237446 directives to 237446 required
27.26 - Hashing Archives
27.26 - Looking for files to hash
27.83 - Found 1501 total files, 1471 matching filesize
28.98 - Downloading Missing Archives
28.99 - Missing 1 archives
28.99 - Getting Nexus API Key, if a browser appears, please accept
29 - Loading server whitelist
29.16 - Loaded permissions for 530 servers and 253 Google Drive files
29.16 - File hash check (-42) f81906cd0ae6fdfd3c28e4c2d9b7bbc57c0c64b8a4a7c8714afb3d41ab7ee613
29.18 - Downloading Elysium - Dyndolod 3D Output (Creation Club).7z
240.09 - Hashed download is incorrect
240.45 - Trying to find solution to broken download for Elysium - Dyndolod 3D Output (Creation Club).7z
240.46 - Looking for generic upgrade for ADA++hie28A= (-4549869168412971008)
240.66 - No solution for broken download Elysium - Dyndolod 3D Output (Creation Club).7z WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/Elysium - Dyndolod 3D Output (Creation Club).7z_e832919a-0da6-489d-b51e-79b95f545b08 could be found
240.86 - Hashing Remaining Archives
240.87 - Looking for files to hash
241.42 - Found 1502 total files, 1472 matching filesize
242.42 - Unable to download Elysium - Dyndolod 3D Output (Creation Club).7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/Elysium - Dyndolod 3D Output (Creation Club).7z_e832919a-0da6-489d-b51e-79b95f545b08)
242.43 - Cannot continue, was unable to download one or more archives
242.43 - File hash check (-42) f81906cd0ae6fdfd3c28e4c2d9b7bbc57c0c64b8a4a7c8714afb3d41ab7ee613
242.44 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
242.59 - File hash check (-42) f81906cd0ae6fdfd3c28e4c2d9b7bbc57c0c64b8a4a7c8714afb3d41ab7ee613

**Comment by ScholarLuma** [comment]
Running into the same error.

**Comment by hubeli** [comment]
Same for me

**Comment by InfernalSaiyan** [comment]
Same. I've tried a dozen times now. And tried messing with every setting in Wabbajack as well as numerous restarts. Followed all instructions. The file even downloads in full. Twice. It refuses to pass the hash check.

**Comment by jfranknichols** [comment]
I see Total Skyrim Overhaul has instructions that something changed recently with MEGA and you have to manually download 10 files and move them to the download directory. Maybe we need to do this for this file? Can we get a link to the file to manually download it while a permanent fix is being worked on?

**Comment by InfernalSaiyan** [comment]
> I see Total Skyrim Overhaul has instructions that something changed recently with MEGA and you have to manually download 

I hope this fixes it. I'm worried it may not because I have the full download from WJ (Seems so anyway) and it just won't hash.

**Comment by cartaah** [comment]
Manual download would be great.

**Comment by ColtonWaldack** [comment]
Same Issue as well.

**Comment by kcowman** [comment]
The files are here. 
https://mega.nz/folder/A1UThCQS#jLZ49eq0xN0kueuejx3hvQ

**Comment by jfranknichols** [comment]
THANK YOU VERY MUCH!

**Comment by cartaah** [comment]
> 
> 
> The files are here.
> https://mega.nz/folder/A1UThCQS#jLZ49eq0xN0kueuejx3hvQ

Thank you, it worked!

**Comment by ColtonWaldack** [comment]
> The files are here.
> https://mega.nz/folder/A1UThCQS#jLZ49eq0xN0kueuejx3hvQ

Thanks so much!

**Comment by glendaion** [comment]
I put the file in the download directory manually. Then continue the installation with wabbajack, but it fails when hashing. I missing something?

**Comment by InfernalSaiyan** [comment]
Also still unable. And of course the file size is just slightly above the free version of MEGA... lol.

**Comment by medinaKrom1** [comment]
Something similar for me.
The via wabbajack downloaded file Elysium - Dyndolod 3D Output (Creation Club).7z is corrupt (testet via 7zip).
With mega.nz I can't download the file reasoned by the file size.

**Comment by Kwebb3304** [comment]
Downloading the file from the MEGA links earlier in the chat helped. The downloaded .zip is named differently (Archive7z I believe). I unzipped that file and I received the file I needed ("Elysium - Dyndolod 3D Output (Creation Club).7z"). I put that file in the "Downloads" folder under my install path and WJ hashed it and successfully completed the install. 

If you have a free MEGA account, then it will tell you to pay or wait 6 hours to continue the download after you hit the limit. I left my browser window open when it finished the timer overnight and it completed the download for me.
