### ISSUE TITLE
Fire Issue after updating

### ISSUE THREAD

**Issue by holt100** [TitansBane/Elysium#16]
Addition of Embers and Fire Combo Patch appears to be causing some issues.  Textures don't show up as in image below.

![ScreenShot0](https://user-images.githubusercontent.com/75289926/100970694-6de79680-3503-11eb-9f3b-6baf2a24ae86.png)

This particular campfire is outside Markarth where the Khajiit set up camp.  Asset is rf-campire-land-on.nif.  Other fire pits also exhibit issues with white assets inside the fire, though it isn't as apparent due to the lighting.

Will do another update through Wabbajack to ensure problem is not just on my end with a broken install.

**Comment by holt100** [comment]
Running another update fixed the issue, apologies for the premature report

**Comment by lilmisslang** [comment]
very curious how you fixed this, because i'm still having the issue and tried updating multiple times now. :L
