### ISSUE TITLE
unable to download TUDM-The Ultimate Doge Moad v4 x63.rar

### ISSUE THREAD

**Issue by CallmeNo** [TitansBane/Elysium#161]

**Comment by CallmeNo** [comment]
i saw this was closed but i dont know how they fixed the issue

**Comment by generalconsensus** [comment]
Same issue, even logged into google and downloaded it from google drive and place it in the downloads folder and still saw an error with hashing...

**Comment by CallmeNo** [comment]
figured it out just put this into the download folder https://drive.google.com/file/d/0B2VgBVA9jE6RTjJiYnRTTE9qRUE/view?resourcekey=0-atMbrLF_HPd3ogbiZaBiXw

**Comment by clausagerskov** [comment]
this should not be closed though if its a bug in the install
