### ISSUE TITLE
EVG Conditional Idles missing MCM menu

### ISSUE THREAD

**Issue by lilmisslang** [TitansBane/Elysium#17]
I may just be dumb, but I've tried reinstalling multiple times now and I can't seem to get the menu to appear. Sorry if I'm just a dumb. 
![SkyrimSE 2020-12-06 00-12-31](https://user-images.githubusercontent.com/75456653/101272182-d7f87980-3757-11eb-983e-00e63f570399.png)

**Comment by TitansBane** [comment]
I went with the no MCM version since I only needed to disable one animation and everything else I was fine with.

**Comment by lilmisslang** [comment]
Oh okie doke. I assume there's probably no way to like.. disable any of them through like console commands or anything? If not, it's cool, just curious.
