### ISSUE TITLE
Dyndolod 3D Output (Creation Club) hashing issue

### ISSUE THREAD

**Issue by Almost-Famous** [TitansBane/Elysium#171]
Creating this issue to hopefully save someone else some time. 

Try enabling the network workaround in WJ's settings if it won't hash. The mega mirror download worked for some people at https://mega.nz/folder/A1UThCQS#jLZ49eq0xN0kueuejx3hvQ but didn't for me.

Cheers

**Comment by Doplauk** [comment]
I'm also having this problem tried downloading your link but didn't solve it for me either, Thanks tho

**Comment by Dahnan** [comment]
None of the four dyndolod 3d output files will download for me either, the above link seems to be for a previous version, I downloaded them but they all fail the hash check.
