### ISSUE TITLE
Unable to download Elisum - Core files.7z

### ISSUE THREAD

**Issue by Tukker4Always** [TitansBane/Elysium#176]
Hi,

i am trying to install 5.5.2, but wabbajack gets stuck on the Elysium - Core files.7z.
I have a download of the file, but probably older version, I put it in the download folder, but WJ ignores it.
Now at 15% download, it stops. Tried to find it on MegaFiles myself, but it says, that files is removed

Michel

**Comment by medinaKrom1** [comment]
Hi, try it again please. It works for me now. Download was not possible before by some reason (maybe not uploaded).

**Comment by Tukker4Always** [comment]
Did you download via WJ or directly on Mega?

**Comment by Tukker4Always** [comment]
WJ is still locked at 10-15%

**Comment by Tukker4Always** [comment]
My file has the wrong HASH file. where can I get the right file

**Comment by TitansBane** [comment]
Redownload the list through the Wabbajack app.
