### ISSUE TITLE
A Bit of a Balancing Issue

### ISSUE THREAD

**Issue by TheGreatAuz** [TitansBane/Elysium#177]
I'm sure you hate hearing from me by now... But I've noticed a bit of a balancing issue while playing through the Legacy of the Dragonborn quests. Essentially the timing of several quests (Most notably the heist quest and the excavation of windcaller pass) have enemies that place them at a vastly superior level to that of the player if the player is going through the normal-ish process of filling up the museum (Jelal is level 85 and I go in at around level 25 and shortly thereafter fighting two dragons at once is fairly difficult to almost impossible under level 30). There are two potential ways to solve this issue, one is to implement changes similar to this mod:

Quest and Reward Delay for Legacy of the Dragonborn:
https://www.nexusmods.com/skyrimspecialedition/mods/44923

The other potential solution is something that I actually don't know if it's possible to implement but would essentially prevent the main armory displays from showing anything unless you crafted it yourself. This second option is one I would consider less desirable, but would technically solve the issue I'm commenting on. Either way this is such a great list I hope my comments are not taken as anything but the most positive and constructive criticism possible. Best wishes!

**Comment by TitansBane** [comment]
Getting added next update.
