### ISSUE TITLE
Irkgnthand consistent crash

### ISSUE THREAD

**Issue by mikey7894** [TitansBane/Elysium#179]
Hello,
I absolutely love your mod list. I didnt think I'd ever play skyrim again until I downloaded your list about a month ago, and have been addicted ever since. Thank you for putting this out to the public like this.

I have a consistent crash trying to enter Irkgnthand. I am on version 5.3.6. I searched the discord, and noticed that you mentioned on 9/13 this issue was going to be fixed in an update. My dilemma is that if I update through wabbajack now, I will have to abandon my character that I've put 71 hours into. Is there any workaround that you know of for this crash without updating to the current version and starting a new character?

**Comment by TitansBane** [comment]
The issue is fixed since version 5.5.3.
