### ISSUE TITLE
Install Cannot be Complete

### ISSUE THREAD

**Issue by RealJawzi** [TitansBane/Elysium#185]
0.2 - Wabbajack Build - fed371a6f1956ee74801c18be22a6d628c68bc0f
0.2 - Running in C:\Wabbajack Modding\2.5.3.1
0.21 - Detected Windows Version: 10.0.19042.0
0.21 - System settings - (31.9GB RAM) (4.8GB Page), Display: 1920 x 1080 (7.8GB VRAM - VideoMemorySizeMb=10240)
0.21 - Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance.
0.22 - Getting new Wabbajack version list
0.22 - Steam: Found no Regex matches in Steam Config at c:/program files (x86)/steam\config\config.vdf
0.22 - Steam: Found no path-matches in Library Folders file at c:/program files (x86)/steam\steamapps\libraryfolders.vdf
0.23 - Steam: Found game New World (1063730) at "c:/program files (x86)/steam\steamapps\common\New World"
0.23 - Steam: Found game DEATH STRANDING (1190460) at "c:/program files (x86)/steam\steamapps\common\Death Stranding"
0.23 - Steam: Found game New World Closed Beta (1205550) at "c:/program files (x86)/steam\steamapps\common\New World Closed Beta"
0.23 - Steam: Found game Steamworks Common Redistributables (228980) at "c:/program files (x86)/steam\steamapps\common\Steamworks Shared"
0.23 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "c:/program files (x86)/steam\steamapps\common\Skyrim Special Edition"
0.23 - GOG: GOG was not found in the registry
0.23 - BethNet: Unable to open Registry Keys SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net and SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net
0.24 - EpicGamesStore: Found game Rocket League® at "C:\Program Files\Epic Games\rocketleague"
0.24 - Origin: LocalContent directory at C:\ProgramData\Origin\LocalContent does not exist
0.5 - Wabbajack Version: 2.5.3.1
0.73 - Build server is alive
0.73 - File hash check (-42) 5a24336f82ad044dc8413e72abcbe2372f5eb364dae48447ef0ad1d1aeb1828c
0.75 - Build server is alive
0.75 - File hash check (-42) 5a24336f82ad044dc8413e72abcbe2372f5eb364dae48447ef0ad1d1aeb1828c
4.49 - Loading ModLists from GitHub
22.72 - Starting to install Elysium
22.73 - Cleaning VFS, this may take a bit of time
22.77 - Starting Installer Task
22.77 - Installation has Started
22.77 - File hash check (-42) 5a24336f82ad044dc8413e72abcbe2372f5eb364dae48447ef0ad1d1aeb1828c
23.14 - Configuring Processor
23.14 - Install Folder: C:\Elysium
23.14 - Downloads Folder: C:\Elysium\downloads
23.14 - Game Folder: c:\program files (x86)\steam\steamapps\common\Skyrim Special Edition
23.14 - Wabbajack Folder: C:\Wabbajack Modding\2.5.3.1
23.14 - Drive watcher is starting. Will warn at 8GB and error at 4GB
23.15 - Starting Drive watcher on C:\ currently 229.7GB free out of 930.9GB
23.15 - Starting Drive watcher on c:\ currently 229.7GB free out of 930.9GB
23.15 - Validating Game ESMs
23.16 - Creating Output Folders
23.21 - Optimizing ModList
23.21 - Optimizing ModList directives
25.32 - Looking for files to delete
25.35 - Cleaning empty folders
26.14 - Looking for unmodified files
26.66 - Updating ModList
26.66 - Optimized 240436 directives to 240436 required
26.71 - Hashing Archives
26.71 - Looking for files to hash
26.84 - Found 1525 total files, 1494 matching filesize
27.02 - Downloading Missing Archives
27.02 - Missing 2 archives
27.02 - Getting Nexus API Key, if a browser appears, please accept
27.03 - Loading server whitelist
27.23 - Loaded permissions for 562 servers and 254 Google Drive files
27.23 - File hash check (-42) 5a24336f82ad044dc8413e72abcbe2372f5eb364dae48447ef0ad1d1aeb1828c
27.29 - Downloading TUDM - The Ultimate Dodge Mod v4 x64.rar
27.29 - Downloading Elysium - Dyndolod 3D Output.7z
27.58 - File hash check (-42) 5a24336f82ad044dc8413e72abcbe2372f5eb364dae48447ef0ad1d1aeb1828c
28.34 - Hashed download is incorrect
28.34 - Loading for alternative to U659DN1scQM=
31.45 - No alternative for U659DN1scQM= could be found
430.82 - Loading for alternative to li/1+qdJ7hc=
431.02 - No alternative for li/1+qdJ7hc= could be found
431.06 - Hashing Remaining Archives
431.06 - Looking for files to hash
431.17 - Found 1525 total files, 1494 matching filesize
464.91 - Unable to download Elysium - Dyndolod 3D Output.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/Elysium - Dyndolod 3D Output.7z_d0fa2e54-afad-44de-910b-7b6fbfd12246)
464.91 - Unable to download TUDM - The Ultimate Dodge Mod v4 x64.rar (GoogleDriveDownloader+State|0B2VgBVA9jE6RTjJiYnRTTE9qRUE)
464.91 - Cannot continue, was unable to download one or more archives
464.91 - File hash check (-42) 5a24336f82ad044dc8413e72abcbe2372f5eb364dae48447ef0ad1d1aeb1828c
464.92 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
465.45 - File hash check (-42) 5a24336f82ad044dc8413e72abcbe2372f5eb364dae48447ef0ad1d1aeb1828c

**Comment by Malazanrake** [comment]
Hi Real Jawzi I have this as well 

34,68 - Downloading TUDM - The Ultimate Dodge Mod v4 x64.rar
34,69 - Downloading Elwaps SpeedTree.7z
35,6 - File hash check (-42) 22c3aaf443fdc95686ac973650d7331cc13cc79af8f08f22fcb3f8f8edcfe784
36,78 - Hashed download is incorrect
36,78 - Loading for alternative to U659DN1scQM=
37,1 - No alternative for U659DN1scQM= could be found
829,88 - Hashing Remaining Archives
829,88 - Looking for files to hash
829,98 - Found 1718 total files, 1504 matching filesize
830,13 - Unable to download TUDM - The Ultimate Dodge Mod v4 x64.rar (GoogleDriveDownloader+State|0B2VgBVA9jE6RTjJiYnRTTE9qRUE)
830,13 - Cannot continue, was unable to download one or more archives
830,14 - File hash check (-42) 22c3aaf443fdc95686ac973650d7331cc13cc79af8f08f22fcb3f8f8edcfe784
830,16 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
831,1 - File hash check (-42) 22c3aaf443fdc95686ac973650d7331cc13cc79af8f08f22fcb3f8f8edcfe784
900,37 - Loading ModLists from GitHub
1995,81 - Loading ModLists from GitHub
2087,33 - Loading ModLists from GitHub
2096,35 - Starting to install Elysium
2096,37 - Starting Installer Task
2096,37 - Installation has Started
2096,37 - File hash check (-42) 22c3aaf443fdc95686ac973650d7331cc13cc79af8f08f22fcb3f8f8edcfe784
2097,38 - Configuring Processor
2097,38 - Install Folder: C:\Elysium
2097,38 - Downloads Folder: C:\Elysium\downloads
2097,38 - Game Folder: C:\Steam\steamapps\common\Skyrim Special Edition
2097,38 - Wabbajack Folder: C:\Wabbajack\2.5.3.1
2097,39 - Drive watcher is starting. Will warn at 8GB and error at 4GB
2097,39 - Starting Drive watcher on C:\ currently 63,9GB free out of 930,8GB
2097,39 - Validating Game ESMs
2097,4 - Creating Output Folders
2097,44 - Caught error getting disk info: Sequence contains no elements. Treating disk as Unspecified.
2097,44 - Optimizing ModList
2097,44 - Optimizing ModList directives
2100,37 - Looking for files to delete
2100,41 - Cleaning empty folders
2101,18 - Looking for unmodified files
2101,64 - Updating ModList
2101,64 - Optimized 240823 directives to 240823 required
2101,7 - Hashing Archives
2101,71 - Looking for files to hash
2101,82 - Found 1699 total files, 1504 matching filesize
2101,98 - Downloading Missing Archives
2101,98 - Missing 1 archives
2101,98 - Getting Nexus API Key, if a browser appears, please accept
2101,98 - Loading server whitelist
2102,39 - Loaded permissions for 562 servers and 254 Google Drive files
2102,39 - File hash check (-42) 22c3aaf443fdc95686ac973650d7331cc13cc79af8f08f22fcb3f8f8edcfe784
2102,47 - Downloading TUDM - The Ultimate Dodge Mod v4 x64.rar
2104,47 - Hashed download is incorrect
2104,47 - Loading for alternative to U659DN1scQM=
2104,88 - No alternative for U659DN1scQM= could be found
2105,05 - Hashing Remaining Archives
2105,05 - Looking for files to hash
2105,16 - Found 1699 total files, 1504 matching filesize
2105,31 - Unable to download TUDM - The Ultimate Dodge Mod v4 x64.rar (GoogleDriveDownloader+State|0B2VgBVA9jE6RTjJiYnRTTE9qRUE)
2105,31 - Cannot continue, was unable to download one or more archives
2105,31 - File hash check (-42) 22c3aaf443fdc95686ac973650d7331cc13cc79af8f08f22fcb3f8f8edcfe784
2105,31 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
2106,26 - File hash check (-42) 22c3aaf443fdc95686ac973650d7331cc13cc79af8f08f22fcb3f8f8edcfe784

I tried to find TUDM - The Ultimate Dodge Mod v4 x64.rar 34,68 -
34,69 - Downloading Elwaps SpeedTree.7z

but i could not, could you please help ?
