### ISSUE TITLE
Is it working properly ? 

### ISSUE THREAD

**Issue by Malazanrake** [TitansBane/Elysium#190]
Hey there

I could install all of it with no error.

" After starting a new game, you will be dropped in the Alternate Start - Live Another Life cell where you can customise your character, then configure your mods before you actually start playing. Stand still and wait until all messages have run through in the upper left corner (check the screenshot below). Then hit ESCAPE and create a manual save before you continue. "

That did not happen to me. 

After starting the game i noticed :

1 - No substitles even if I select them to be displayed (I play in english but i'd like english substitles)
2 - It starts @Helgen  I thought we would start with START ANOTHER LIFE mod. I can see the mode ticked and active in MO2.
3 - In the game, MOD menu is empty but the surrounding landscapes are great so definetly modded
4 - When I do start the game using the Top right RUN Elysium SKSE in MO2, it keeps asking if it should start steam or not.

Please note that I did a clean uninstall and reinstall  of the game in C: via steam and as said, all the process of installing ELYSIUM was made with no error.

Can someone help ? I 'm running it on WIN 11.

Thanks

**Comment by S-w-y-l-e-r** [comment]
"4 - When I do start the game using the Top right RUN Elysium SKSE in MO2, it keeps asking if it should start steam or not."

To launch Skyrim with Elysium you need to run "Elysium SKSE" in MO2... can you not get past the "start steam" question?  If you are starting Skyrim by starting "SkyrimSE.exe" then you are starting the game without the modlist.

**Comment by Malazanrake** [comment]
nobody ?
