### ISSUE TITLE
Low FPS and Long Load times.

### ISSUE THREAD

**Issue by Kurumi78** [TitansBane/Elysium#20]
I have experienced some bad FPS issues and extremely long load times.

My CPU is a Ryzen 5 2600x
My Graphics Card is a Geforce 1660Ti
The game is running off of a 7200RPM hard drive, but windows is installed to a separate SSD

Load times for the main open world would sometimes take 4 minutes or so, and im seeing 20-40FPS depending on the area. Is this unusually low for the hardware im running it on, or is there something else up?

**Comment by Lunaeries** [comment]
Wait what's the answer. I have the same specs, just got the mod. Can't find anywhere that suggests recommended specs.

**Comment by Kurumi78** [comment]
Exact reason I asked.

**Comment by Kurumi78** [comment]
Exact reason I asked.

**Comment by Lunaeries** [comment]
Welp. Kurumi, I looked into it a bit and a 1660 ti as a gpu can handle it relatively smoothly. About 30fps standard. But moving some hardware around, having about 32gb RAM and upgrading to a 10th gen i7 gets rid of a lot of the occasional fps drop. Probably has more to do with the CPU than the RAM but this mods force the PC to use more than usual.

**Comment by DrGirlfriend** [comment]
I was in the same position. In MO2, scroll down in the left panel to 39 Performance Mode and expand it's list, check the box next to No Grass In Objects, then launch Skyrim. The creator of this mod pack seems to close issues with no comments nor link duplicates.
