### ISSUE TITLE
Download/Hashing Issue for 2 Files

### ISSUE THREAD

**Issue by badtouchexample** [TitansBane/Elysium#200]
Hello, I've had problems completing the download process because of two files:

Elysium - Dyndolod 3D Output (Creation Club)_5e0ec19e394657f1c7d180676664d636a3f994f28bc6169ca63b84e916e33b42_
Elysium - Dyndolod 3D Output_305280ce9a113a4e2cd03a08dc9ab0321da74c4ec568da3dbd5e8d571de65cc1_

The files seem to complete their download but cause  an installation failure and seem to redownload themselves on each retry.

![7zip error](https://user-images.githubusercontent.com/93489422/139597349-7728b5c5-61f7-4c1b-a5be-18f62857c1b0.jpg)
![hashed download](https://user-images.githubusercontent.com/93489422/139597462-1dcb246d-a5e0-4b8e-b559-623930572a21.jpg)

Looking forward to playing Elysium once this has been resolved, thanks very much for your hard work.

**Comment by medinaKrom1** [comment]
Maybe this can help you:
I had to create an account for MEGA and bought the minimum upgrade package to download files larger than 5GB in one piece. You also have to give Wabbajack the MEGA login in the settings.

**Comment by badtouchexample** [comment]
> Maybe this can help you: I had to create an account for MEGA and bought the minimum upgrade package to download files larger than 5GB in one piece. You also have to give Wabbajack the MEGA login in the settings.

I'll give that a go, thanks for the tip!

**Comment by badtouchexample** [comment]
> > Maybe this can help you: I had to create an account for MEGA and bought the minimum upgrade package to download files larger than 5GB in one piece. You also have to give Wabbajack the MEGA login in the settings.
> 
> I'll give that a go, thanks for the tip!


Unfortunately this didn't fix the issue, the files downloaded completely and I was even able to open them but the wabbajack installer keeps failing.

**Comment by medinaKrom1** [comment]
This hash error occurs if the download was not correctly finished. Usually the reason is the 5 GB limit with standard mega account. I had the same error before I did the MEGA setup correctly.

Are you sure you bought the MEGA Pro Lite Upgrade for your MEGA account?
![image](https://user-images.githubusercontent.com/84533669/139666669-a75739c7-0879-46b1-a19c-11afc1bf2332.png)

.. and the setup in Wabbajack?
![image](https://user-images.githubusercontent.com/84533669/139666749-b392bb54-f5f0-4ef0-8b82-79bc3b141078.png)

By the way: sometimes connection problems can be the reason too, but at least after trying it two times worked for me.

**Comment by focused** [comment]
What happens if you try the "network workaround" setting?
P.S.: I downloaded this one successfully, maybe it occurs for other people...

**Comment by badtouchexample** [comment]
On checking my MEGA account I was definitely on the Pro Lite on my later attempt. The files seemed to complete in their full 5+ Gb sizes and I was able to open them in winzip and view their contents without the error I was getting before, however they still weren’t hashing during the install. I’ve since been able to complete the install but only after downloading the files hosted elsewhere provided by the elysium discord group.

Curious that they correctly work for other people, hopefully my issue was a one off but if anyone else has the same problem with the files hosted on MEGA they might need to be checked. 

Thanks for all the advice.
