### ISSUE TITLE
Skyrim windows edition not working

### ISSUE THREAD

**Issue by LiaanSage** [TitansBane/Elysium#202]
Skyrim windows edition the wabbjack app only tells me that game installation is not found ? does the app not work for windows edition ? or what am I missing?

**Comment by focused** [comment]
What is "Skyrim windows edition"? I use the Steam version and WJ finds it correctly.

**Comment by LiaanSage** [comment]
skyrim via the windows store.

**Comment by focused** [comment]
Sorry, I don't know how to help, it's worth posting this issue to Wabbajack directly. This is not the issue with the Elysium mod list itself, it's the WJ problem.

**Comment by medinaKrom1** [comment]
I think Skyrim is creating a registry key after the first start with the folder path to the game. 
The "Skyrim Special Edition" from this strange MStore theoretically should do the same, but who knows what Microsoft changed to offer the game there. Better using steam as most people too).
Maybe you should post a screenshot from the Wabbajack error.

**Comment by focused** [comment]
Please do it in the WJ repo, I believe it's not related to Elysium only.
https://github.com/wabbajack-tools/wabbajack/issues
