### ISSUE TITLE
unable to hash/download multiple files

### ISSUE THREAD

**Issue by rene0121** [TitansBane/Elysium#204]
![image](https://user-images.githubusercontent.com/88949783/139801319-43047eed-49f5-4856-92fc-fca6019a41b9.png)
multiple hash/download errors anyone have a solution?

**Comment by focused** [comment]
See pins in the channel! https://discord.com/channels/552625087438782474/882031813676126298/887943409250213918

**Comment by AppZ1337** [comment]
I got the Same Problem - but the link you Posted only directs me to an empty discord pag
![discord server problem](https://user-images.githubusercontent.com/93646928/140034816-838161e1-8f48-422f-9456-1eee1436224a.PNG)
e

**Comment by focused** [comment]
I don't know if it works, but I copied the invitation link https://discord.gg/9meHMG3y

**Comment by focused** [comment]
This link should work https://discord.com/invite/VVHRJeK
