### ISSUE TITLE
WJ Unable to download Elysium - Dyndolod 3D Output*.7z files; causes install to fail

### ISSUE THREAD

**Issue by lconover** [TitansBane/Elysium#212]
During Wabbajack download, I am having repeated failures with multiple  Dyndolod 3D Output*.7z files.  Repeat attempts over the last few days have all failed in the same manner.  

The logging is as follows:

```
1027.92 - Unable to download Elysium - Dyndolod 3D Output.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/Elysium - Dyndolod 3D Output.7z_b3e81829-8133-43c2-a2bf-607121d59fd3)
1027.92 - Unable to download Elysium - Dyndolod 3D Output (Creation Club).7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/Elysium - Dyndolod 3D Output (Creation Club).7z_3aa777cd-6677-4077-83d5-7bc5ab81ceaf)
1027.92 - Cannot continue, was unable to download one or more archives
```
Mysteriously, files do seem to be getting downloaded with those names into the download directory; perhaps they are corrupt or have the wrong checksum?  I have tried manually deleting them and redownloading them to the same result.   

```
11/07/2021  03:44 PM     1,092,853,431 Elysium - Dyndolod 3D Output - Performance Mode (Creation Club).7z
11/07/2021  03:47 PM     1,090,992,068 Elysium - Dyndolod 3D Output - Performance Mode.7z
11/10/2021  04:28 PM     6,272,625,307 Elysium - Dyndolod 3D Output_90e453f285705a0e77ddcc67aa8d25b807d712357c8fc0efe754d8a7c44753a1_.7z
11/10/2021  04:28 PM     6,277,667,868 Elysium - Dyndolod 3D Output (Creation Club)_3c17bb050cb6e69397d52be6eb03d465c9d45e069f47d5bb387ce5b28f5d26cc_.7z
```
Full logfile is attached.   In case it matters, this is happening on Windows 10.  
[Wabbajack.current.log](https://github.com/TitansBane/Elysium/files/7516104/Wabbajack.current.log)

**Comment by TwistedHumors** [comment]
1597.49 - Downloading Elysium - Dyndolod 3D Output.7z
1597.64 - File hash check (-42) 9a0ee4d2075116f00c4bcbbf429d8cdc0afcafea287241c7b003cdac10b4c45d
1781.65 - Loading for alternative to k6V+p1NaTWI=
1781.75 - No alternative for k6V+p1NaTWI= could be found
1781.97 - Hashing Remaining Archives
1781.97 - Looking for files to hash
1782.21 - Found 2848 total files, 1576 matching filesize
1829.67 - Unable to download Elysium - Dyndolod 3D Output.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/Elysium - Dyndolod 3D Output.7z_b3e81829-8133-43c2-a2bf-607121d59fd3)
1829.67 - Cannot continue, was unable to download one or more archives
Here is the full file, similar issue I think.
[Wabbajack.current.log](https://github.com/TitansBane/Elysium/files/7517187/Wabbajack.current.log)
