### ISSUE TITLE
Installation failed after dowloading archives

### ISSUE THREAD

**Issue by FunkyBonks** [TitansBane/Elysium#214]
After downlading 1532 archives, pops a message that the installation failed.
"Cannot continue, was unable to download one or more archives"

It posts some messages about one mod (The Ultimate Dodge Mod) and other basic skyrim files (animations.bsa, misc.bsa and other .bsa files)
I've tried reinstalling the missing archives, but it takes me to a loop:
- Downloading 19 missing archives
- Fails on each one, prompts a "No alternative for {random hash}"
- And Begins installing and fails immediatly with the above error 

Adding the latest log files, generates the same output everytime
[Wabbajack.current.log](https://github.com/TitansBane/Elysium/files/7527655/Wabbajack.current.log)

**Comment by ky36789** [comment]
im in the same boat

**Comment by IDigitalNomadI** [comment]
Me too .. exactly the same error

**Comment by FunkyBonks** [comment]
Have you guys also installed the anniversary update? Maybe it messes the basic skyrim files up?

**Comment by ky36789** [comment]
I used the downgrade tool so its not the anniversary update.

**Comment by FunkyBonks** [comment]
And still having the same problems? Or is it fixed?

**Comment by FunkyBonks** [comment]
@TitansBane don't want to be an hassle, but would really appreciate your help here
Really wanna play your modpack, since it's the only one for SE with TDM, aside from the visuals and crazy amount of content
Still having the same issue, and yesterday I saw the modlist was in development, hoping for a fix but saddly that hasn't fixed my issue.
Still saying that the files are missing, and I've checked the downloads folder and all the files are inside the folder, yet WJ tries to download everytime and fails for "unable to download one or more archives"

Readding the latest log file
[Wabbajack.current.log](https://github.com/TitansBane/Elysium/files/7534459/Wabbajack.current.log)

**Comment by welch3694** [comment]
@FunkyBonks and anyone else looking for this -- 

The issue is that you probably have the Skyrim SE Anniversary Edition update, go here and use this (get the FullPatcher.zip, extract, run patcher.exe) https://www.nexusmods.com/skyrimspecialedition/mods/57618 -- this downgrades your game to the non-Anniversary edition, which works with everything else.

After doing that and trying to reinstall the modpack via Wabbajack, you will still get an issue with The Ultimate Dodge Mod, so go get the file, linked here from another issue: https://github.com/TitansBane/Elysium/issues/188#issuecomment-938551236

Download that, paste it into your Elysium download directory (overwrite the file that is already there), and then in Wabbajack, do Install From Disk, and it should select Elysium, and it will then proceed to extracting everything and installing.

**Comment by yanlcd** [comment]
Hi,

Thanks for the help the Patch fixed it for the .bsa files. But it's still the same issue for the Skyrim_Default.ini (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|skyrim_default.ini)
From what I have seen it could be the language so I set it on ENGLISH

Here is the Wabbajack log
[Wabbajack.current.log](https://github.com/TitansBane/Elysium/files/7534961/Wabbajack.current.log)

Here is the ini file

[General]
sLanguage=ENGLISH
sTestFile1=Dawnguard.esm
sTestFile2=HearthFires.esm
sTestFile3=Dragonborn.esm

uExterior Cell Buffer=36

[Display]
fShadowLODMaxStartFade=1000.0
fSpecularLODMaxStartFade=2000.0
fLightLODMaxStartFade=3500.0
fLightLODStartFade=3500.0
iShadowMapResolutionPrimary=2048
bAllowScreenshot=1
fTreesMidLODSwitchDist=9999999.0000
fFirstSliceDistance=2000.0000
fDynamicDOFFarBlur=0.4
fDDOFFocusCenterweightExt=2
fDOFMaxDepthParticipation=10000

[Audio]
fMusicDuckingSeconds=6.0
fMusicUnDuckingSeconds=8.0
fMenuModeFadeOutTime=3.0
fMenuModeFadeInTime=1.0

[Grass]
bAllowCreateGrass=1
bAllowLoadGrass=0
fGrassMaxStartFadeDistance=7000.0000
fGrassMinStartFadeDistance=0.0000

[Decals]
uMaxSkinDecalPerActor=60

[LightingShader]
fDecalLODFadeStart=0.45
fDecalLODFadeEnd=0.5

[Imagespace]
iRadialBlurLevel=2

[GeneralWarnings]
SGeneralMasterMismatchWarning=One or more plugins could not find the correct versions of the master files they depend on. Errors may occur during load or game play. Check the "Warnings.txt" file for more information.

[Archive]
sResourceArchiveList=Skyrim - Misc.bsa, Skyrim - Shaders.bsa, Skyrim - Interface.bsa, Skyrim - Animations.bsa, Skyrim - Meshes0.bsa, Skyrim - Meshes1.bsa, Skyrim - Sounds.bsa
sResourceArchiveList2=Skyrim - Voices_fr0.bsa, Skyrim - Textures0.bsa, Skyrim - Textures1.bsa, Skyrim - Textures2.bsa, Skyrim - Textures3.bsa, Skyrim - Textures4.bsa, Skyrim - Textures5.bsa, Skyrim - Textures6.bsa, Skyrim - Textures7.bsa, Skyrim - Textures8.bsa, Skyrim - Patch.bsa
bLoadArchiveInMemory=1
sArchiveToLoadInMemoryList=Skyrim - Animations.bsa

[Combat]
fMagnetismStrafeHeadingMult=0.0
fMagnetismLookingMult=0.0

[Actor]
bUseNavMeshForMovement=0

[Papyrus]
fPostLoadUpdateTimeMS=500.0
bEnableLogging=0
bEnableTrace=0
bLoadDebugInformation=0

**Comment by Dadi980** [comment]
> Hi,
> 
> Thanks for the help the Patch fixed it for the .bsa files. But it's still the same issue for the Skyrim_Default.ini (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|skyrim_default.ini) From what I have seen it could be the language so I set it on ENGLISH
> 
> Here is the Wabbajack log [Wabbajack.current.log](https://github.com/TitansBane/Elysium/files/7534961/Wabbajack.current.log)
> 
> Here is the ini file
> 
> [General] sLanguage=ENGLISH sTestFile1=Dawnguard.esm sTestFile2=HearthFires.esm sTestFile3=Dragonborn.esm
> 
> uExterior Cell Buffer=36
> 
> [Display] fShadowLODMaxStartFade=1000.0 fSpecularLODMaxStartFade=2000.0 fLightLODMaxStartFade=3500.0 fLightLODStartFade=3500.0 iShadowMapResolutionPrimary=2048 bAllowScreenshot=1 fTreesMidLODSwitchDist=9999999.0000 fFirstSliceDistance=2000.0000 fDynamicDOFFarBlur=0.4 fDDOFFocusCenterweightExt=2 fDOFMaxDepthParticipation=10000
> 
> [Audio] fMusicDuckingSeconds=6.0 fMusicUnDuckingSeconds=8.0 fMenuModeFadeOutTime=3.0 fMenuModeFadeInTime=1.0
> 
> [Grass] bAllowCreateGrass=1 bAllowLoadGrass=0 fGrassMaxStartFadeDistance=7000.0000 fGrassMinStartFadeDistance=0.0000
> 
> [Decals] uMaxSkinDecalPerActor=60
> 
> [LightingShader] fDecalLODFadeStart=0.45 fDecalLODFadeEnd=0.5
> 
> [Imagespace] iRadialBlurLevel=2
> 
> [GeneralWarnings] SGeneralMasterMismatchWarning=One or more plugins could not find the correct versions of the master files they depend on. Errors may occur during load or game play. Check the "Warnings.txt" file for more information.
> 
> [Archive] sResourceArchiveList=Skyrim - Misc.bsa, Skyrim - Shaders.bsa, Skyrim - Interface.bsa, Skyrim - Animations.bsa, Skyrim - Meshes0.bsa, Skyrim - Meshes1.bsa, Skyrim - Sounds.bsa sResourceArchiveList2=Skyrim - Voices_fr0.bsa, Skyrim - Textures0.bsa, Skyrim - Textures1.bsa, Skyrim - Textures2.bsa, Skyrim - Textures3.bsa, Skyrim - Textures4.bsa, Skyrim - Textures5.bsa, Skyrim - Textures6.bsa, Skyrim - Textures7.bsa, Skyrim - Textures8.bsa, Skyrim - Patch.bsa bLoadArchiveInMemory=1 sArchiveToLoadInMemoryList=Skyrim - Animations.bsa
> 
> [Combat] fMagnetismStrafeHeadingMult=0.0 fMagnetismLookingMult=0.0
> 
> [Actor] bUseNavMeshForMovement=0
> 
> [Papyrus] fPostLoadUpdateTimeMS=500.0 bEnableLogging=0 bEnableTrace=0 bLoadDebugInformation=0
Yeah im stuck at the same step. was pretty hyped to play thit list but can´t make it work.

**Comment by Dadi980** [comment]
> Hi,
> 
> Thanks for the help the Patch fixed it for the .bsa files. But it's still the same issue for the Skyrim_Default.ini (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|skyrim_default.ini) From what I have seen it could be the language so I set it on ENGLISH
> 
> Here is the Wabbajack log [Wabbajack.current.log](https://github.com/TitansBane/Elysium/files/7534961/Wabbajack.current.log)
> 
> Here is the ini file
> 
> [General] sLanguage=ENGLISH sTestFile1=Dawnguard.esm sTestFile2=HearthFires.esm sTestFile3=Dragonborn.esm
> 
> uExterior Cell Buffer=36
> 
> [Display] fShadowLODMaxStartFade=1000.0 fSpecularLODMaxStartFade=2000.0 fLightLODMaxStartFade=3500.0 fLightLODStartFade=3500.0 iShadowMapResolutionPrimary=2048 bAllowScreenshot=1 fTreesMidLODSwitchDist=9999999.0000 fFirstSliceDistance=2000.0000 fDynamicDOFFarBlur=0.4 fDDOFFocusCenterweightExt=2 fDOFMaxDepthParticipation=10000
> 
> [Audio] fMusicDuckingSeconds=6.0 fMusicUnDuckingSeconds=8.0 fMenuModeFadeOutTime=3.0 fMenuModeFadeInTime=1.0
> 
> [Grass] bAllowCreateGrass=1 bAllowLoadGrass=0 fGrassMaxStartFadeDistance=7000.0000 fGrassMinStartFadeDistance=0.0000
> 
> [Decals] uMaxSkinDecalPerActor=60
> 
> [LightingShader] fDecalLODFadeStart=0.45 fDecalLODFadeEnd=0.5
> 
> [Imagespace] iRadialBlurLevel=2
> 
> [GeneralWarnings] SGeneralMasterMismatchWarning=One or more plugins could not find the correct versions of the master files they depend on. Errors may occur during load or game play. Check the "Warnings.txt" file for more information.
> 
> [Archive] sResourceArchiveList=Skyrim - Misc.bsa, Skyrim - Shaders.bsa, Skyrim - Interface.bsa, Skyrim - Animations.bsa, Skyrim - Meshes0.bsa, Skyrim - Meshes1.bsa, Skyrim - Sounds.bsa sResourceArchiveList2=Skyrim - Voices_fr0.bsa, Skyrim - Textures0.bsa, Skyrim - Textures1.bsa, Skyrim - Textures2.bsa, Skyrim - Textures3.bsa, Skyrim - Textures4.bsa, Skyrim - Textures5.bsa, Skyrim - Textures6.bsa, Skyrim - Textures7.bsa, Skyrim - Textures8.bsa, Skyrim - Patch.bsa bLoadArchiveInMemory=1 sArchiveToLoadInMemoryList=Skyrim - Animations.bsa
> 
> [Combat] fMagnetismStrafeHeadingMult=0.0 fMagnetismLookingMult=0.0
> 
> [Actor] bUseNavMeshForMovement=0
> 
> [Papyrus] fPostLoadUpdateTimeMS=500.0 bEnableLogging=0 bEnableTrace=0 bLoadDebugInformation=0


Yeah im stuck at the same step as you. I can´t get this modlist to work.

**Comment by Lupertos** [comment]
Hi.

I have the same issue with the Skyrim_default.ini. I have tried to change the language but nothing happens and the issue is almost there. :-(

@welch3694 Do you have an idea how to fix that as well? I have followed your hints you mentioned before and it helps to fix the most of the issue. But the default.ini one leaves! 

16,71 - Found 1595 total files, 1554 matching filesize
16,94 - Unable to download Skyrim_Default.ini (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|skyrim_default.ini)
16,94 - Cannot continue, was unable to download one or more archives
16,94 - File hash check (-42) f35dcfd8e6bdecfdb53f00dcce06cf66c7abbe392fe5a2273541977913782119
16,96 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives

Thanks! ;-)

**Comment by Draryu** [comment]
for default.ini set game in STEAM TO English

**Comment by Lupertos** [comment]
> for default.ini set game in STEAM TO English

Thanks. That's it. Now it works
