### ISSUE TITLE
Unable to download "Elysium - Dynolod 3D Output"

### ISSUE THREAD

**Issue by mathesoncd** [TitansBane/Elysium#217]
When attempting to install the modlist wabbajack fails when trying to download the Dynolod output. I have run the full AE downgrader so Im positive its not this.

Pertinent log information below

`7390.32 - Unable to download Elysium - Dyndolod 3D Output.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/Elysium - Dyndolod 3D Output.7z_b3e81829-8133-43c2-a2bf-607121d59fd3)
7390.32 - Unable to download Elysium - Dyndolod 3D Output (Creation Club).7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/Elysium - Dyndolod 3D Output (Creation Club).7z_3aa777cd-6677-4077-83d5-7bc5ab81ceaf)
7390.32 - Cannot continue, was unable to download one or more archives
7390.32 - File hash check (-42) 19157def42b181e36d2b3736b7ad2ee8f989ea1bc3fe3e13b84fc36a820e59f2
7390.32 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
7390.51 - File hash check (-42) 19157def42b181e36d2b3736b7ad2ee8f989ea1bc3fe3e13b84fc36a820e59f2
`

**Comment by Draryu** [comment]
same problem , you have a solution ?

**Comment by mathesoncd** [comment]
Yeahp, the issue is that those files are now hosted on MEGA and are larger than the free user download limit, so when it cuts you off wabbajack thinks it's done and tries to move on with files that won't work in the end. 

Solution was to buy a month of MEGA and connect the account in wabbajack's settings and delete the previous failed download

**Comment by l0wPoWa** [comment]
I have the same proble, but none of the current "solutions" worked for me. I have MEGA premium for 1 month and i allowed Wabbajack to enter MEGA with my credentials, still hash fail and it will not start download. (deleted unfinished files before)
I dowloaded it manually from MEGA and pasted it into the download folder, still Wabbajack will generate hash error (same as in the opening post). I tried to unzip the files from these two pack, same error. Any suggestions? I'm clueless what should i do. Thanks in advance.

Logs below:

44,45 - Validating Game ESMs
44,47 - Creating Output Folders
44,82 - Caught error getting disk info: Sequence contains no elements. Treating disk as Unspecified.
44,82 - Optimizing ModList
44,82 - Optimizing ModList directives
49,44 - Looking for files to delete
49,45 - Cleaning empty folders
51 - Looking for unmodified files
51,85 - Updating ModList
51,85 - Optimized 241594 directives to 241594 required
51,92 - Hashing Archives
51,92 - Looking for files to hash
53,28 - Found 1556 total files, 1547 matching filesize
53,69 - Downloading Missing Archives
53,7 - Missing 4 archives
53,7 - Getting Nexus API Key, if a browser appears, please accept
53,7 - Loading server whitelist
54 - Loaded permissions for 642 servers and 284 Google Drive files
54 - File hash check (-42) 2e737aa1574cafcf6787e78b43edefe7e74944ca8c04c08f0ee26381c1ee64ab
54,03 - Downloading Nemesis.Unlimited.Behavior.Engine.v0.84-beta.rar
54,04 - Downloading Elysium - Dyndolod 3D Output.7z
54,04 - Downloading xLODGen.84.7z
54,04 - Downloading Elysium - Dyndolod 3D Output (Creation Club).7z
54,36 - Loading for alternative to uq8KT2b+f9A=
54,45 - File hash check (-42) 2e737aa1574cafcf6787e78b43edefe7e74944ca8c04c08f0ee26381c1ee64ab
54,75 - No alternative for uq8KT2b+f9A= could be found
54,94 - Loading for alternative to Ypeg2MKgzlQ=
54,97 - File hash check (-42) 2e737aa1574cafcf6787e78b43edefe7e74944ca8c04c08f0ee26381c1ee64ab
56,37 - No alternative for Ypeg2MKgzlQ= could be found
