### ISSUE TITLE
Console commands TGM and TIM are disabled at game start and cannot be enabled

### ISSUE THREAD

**Issue by lconover** [TitansBane/Elysium#218]
TGM (god mode) and TIM (immortal mode) are being disabled from the very start of the game, even when I reinstalled Elysium without the Creation Club mod packs being present.  (Survival mode is known to have this same effect.  I've tried this with and without the Creation Club mods present, and both have the same result.)

Thank you so much for looking into this; I absolutely love playing Elysium; it's one of the most gorgeous reworks of Skyrim I've experienced.

While I know it's wimpy to play using these modes, for gamers like me who actually prefer playing through Skyrim more to see the story than to experience the combat, I often rely on them so that I can be a 'tourist' in the game, or get through situations where the modded difficulty level is simply impossible.  (I suppose I can probably use the individual kill commands, but that seems even more disruptive to immersion.)

**Comment by RPR0001** [comment]
marked as closed, safe to say it's supposed to be this way? kinda bummer if it is.. i'm with op on this one

**Comment by RPR0001** [comment]
> marked as closed, safe to say it's supposed to be this way? kinda bummer if it is.. i'm with op on this one

EDIT to OP: edit po3_Tweaks.ini (in X:\Elysium Remastered\mods\Elysium Remastered - Patches\SKSE\Plugins). there's the option inside to enable god mode
