### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Leo1992pl** [TitansBane/Elysium#219]
Hello guys!  
It goes like that:   

23,03 - Found 1604 total files, 1543 matching filesize

23,33 - Downloading Missing Archives

23,34 - Missing 11 archives

23,34 - Getting Nexus API Key, if a browser appears, please accept

23,35 - Loading server whitelist

23,63 - Loaded permissions for 580 servers and 263 Google Drive files

23,63 - File hash check (-42) 9c331ca6d22b73ab51a31b96d4ffb9122cb0b88887080535c7c67b2b20f721ef

23,68 - Downloading Data\_Skyrim - Textures0.bsa

23,69 - Downloading Data\_Skyrim - Textures3.bsa

23,69 - Downloading Data\_Skyrim.esm

23,69 - Downloading Data\_Skyrim - Sounds.bsa

27,65 - Hashed download is incorrect

27,65 - Loading for alternative to krNnq2qHmOo=

27,84 - No alternative for krNnq2qHmOo= could be found

27,85 - Downloading Data\_Skyrim - Shaders.bsa

29,3 - Hashed download is incorrect

29,3 - Loading for alternative to yRcX3Ttf9YM=

29,47 - No alternative for yRcX3Ttf9YM= could be found

29,47 - Downloading Data\_Skyrim - Patch.bsa

29,47 - (Retry 1 of 5), got exception (2) Nie można odnaleźć określonego pliku: \[D:\\gry\\steam\\steamapps\\common\\Skyrim Special Edition\\Data\\Skyrim - Patch.bsa\], waiting 100ms

29,57 - (Retry 2 of 5), got exception (2) Nie można odnaleźć określonego pliku: \[D:\\gry\\steam\\steamapps\\common\\Skyrim Special Edition\\Data\\Skyrim - Patch.bsa\], waiting 200ms

29,77 - (Retry 3 of 5), got exception (2) Nie można odnaleźć określonego pliku: \[D:\\gry\\steam\\steamapps\\common\\Skyrim Special Edition\\Data\\Skyrim - Patch.bsa\], waiting 400ms

30,19 - (Retry 4 of 5), got exception (2) Nie można odnaleźć określonego pliku: \[D:\\gry\\steam\\steamapps\\common\\Skyrim Special Edition\\Data\\Skyrim - Patch.bsa\], waiting 800ms

30,99 - (Retry 5 of 5), got exception (2) Nie można odnaleźć określonego pliku: \[D:\\gry\\steam\\steamapps\\common\\Skyrim Special Edition\\Data\\Skyrim - Patch.bsa\], waiting 1600ms

32,61 - Loading for alternative to GG4pOfUmiRA=

32,75 - No alternative for GG4pOfUmiRA= could be found

32,75 - Downloading Data\_Skyrim - Misc.bsa

34,9 - Hashed download is incorrect

34,9 - Loading for alternative to EwvbU7wcUUo=

35,14 - No alternative for EwvbU7wcUUo= could be found

35,14 - Downloading Data\_Skyrim - Meshes1.bsa

37,86 - Hashed download is incorrect

37,86 - Loading for alternative to /Sglpr+ZffA=

38,05 - No alternative for /Sglpr+ZffA= could be found

38,05 - Downloading Data\_Skyrim - Meshes0.bsa

40,99 - Hashed download is incorrect

40,99 - Loading for alternative to eN9rU4PSvEs=

41,19 - No alternative for eN9rU4PSvEs= could be found

41,19 - Downloading Data\_Skyrim - Interface.bsa

42,03 - Hashed download is incorrect

42,03 - Loading for alternative to k5EWx/9Woqg=

42,22 - No alternative for k5EWx/9Woqg= could be found

42,22 - Downloading Data\_Update.esm

42,44 - Hashed download is incorrect

42,44 - Loading for alternative to /DLG/LjdGXI=

42,62 - No alternative for /DLG/LjdGXI= could be found

45,74 - Hashed download is incorrect

45,74 - Loading for alternative to rENi4TDkFjY=

45,95 - No alternative for rENi4TDkFjY= could be found

46,89 - Hashed download is incorrect

46,89 - Loading for alternative to 8LzXRU4x9Sw=

47,07 - No alternative for 8LzXRU4x9Sw= could be found

55,19 - Hashed download is incorrect

55,19 - Loading for alternative to XTaNNFIm3eM=

55,39 - No alternative for XTaNNFIm3eM= could be found

55,43 - Hashing Remaining Archives

55,43 - Looking for files to hash

55,62 - Found 1604 total files, 1543 matching filesize

55,97 - Unable to download Data\_Update.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\\update.esm)

55,97 - Unable to download Data\_Skyrim - Interface.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\\skyrim - interface.bsa)

55,97 - Unable to download Data\_Skyrim - Meshes0.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\\skyrim - meshes0.bsa)

55,98 - Unable to download Data\_Skyrim - Meshes1.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\\skyrim - meshes1.bsa)

55,98 - Unable to download Data\_Skyrim - Misc.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\\skyrim - misc.bsa)

55,98 - Unable to download Data\_Skyrim - Patch.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\\skyrim - patch.bsa)

55,98 - Unable to download Data\_Skyrim - Shaders.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\\skyrim - shaders.bsa)

55,98 - Unable to download Data\_Skyrim - Sounds.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\\skyrim - sounds.bsa)

55,98 - Unable to download Data\_Skyrim.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\\skyrim.esm)

55,98 - Unable to download Data\_Skyrim - Textures3.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\\skyrim - textures3.bsa)

55,98 - Unable to download Data\_Skyrim - Textures0.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\\skyrim - textures0.bsa)

55,98 - Cannot continue, was unable to download one or more archives

55,98 - File hash check (-42) 9c331ca6d22b73ab51a31b96d4ffb9122cb0b88887080535c7c67b2b20f721ef

56,03 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives

   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\\actions-runner\\\_work\\wabbajack\\wabbajack\\Wabbajack.Lib\\AInstaller.cs:line 70

   at Wabbajack.Lib.MO2Installer.\_Begin(CancellationToken cancel) in C:\\actions-runner\\\_work\\wabbajack\\wabbajack\\Wabbajack.Lib\\MO2Installer.cs:line 161

   at Wabbajack.Lib.ABatchProcessor.<Begin>b\_\_66\_0() in C:\\actions-runner\\\_work\\wabbajack\\wabbajack\\Wabbajack.Lib\\ABatchProcessor.cs:line 177

   at Wabbajack.MO2InstallerVM.<>c\_\_DisplayClass31\_0.<<Install>b\_\_0>d.MoveNext() in C:\\actions-runner\\\_work\\wabbajack\\wabbajack\\Wabbajack\\View Models\\Installers\\MO2InstallerVM.cs:line 181

\--- End of stack trace from previous location ---

   at Wabbajack.MO2InstallerVM.Install() in C:\\actions-runner\\\_work\\wabbajack\\wabbajack\\Wabbajack\\View Models\\Installers\\MO2InstallerVM.cs:line 175

   at Wabbajack.InstallerVM.<>c\_\_DisplayClass85\_0.<<-ctor>b\_\_75>d.MoveNext() in C:\\actions-runner\\\_work\\wabbajack\\wabbajack\\Wabbajack\\View Models\\Installers\\InstallerVM.cs:line 383

56,75 - File hash check (-42) 9c331ca6d22b73ab51a31b96d4ffb9122cb0b88887080535c7c67b2b20f721ef

  
I've tried  Unofficial Skyrim Special Edition Downgrade Patcher, both versions and reinstalling. Nothing helps. You're my last hope!

**Comment by Crazydude12** [comment]
Yeah having the same :( 100gb sitting there and can't do anything with it..

**Comment by motte49** [comment]
570,19 - Unable to download binkw64.dll (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|binkw64.dll)
570,19 - Unable to download Skyrim.ccc (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|skyrim.ccc)
570,19 - Unable to download SkyrimSE.exe (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|skyrimse.exe)
570,19 - Unable to download Skyrim_Default.ini (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|skyrim_default.ini)
570,19 - Unable to download Elysium - Dyndolod 3D Output (Creation Club).7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/Elysium - Dyndolod 3D Output (Creation Club).7z_3aa777cd-6677-4077-83d5-7bc5ab81ceaf)
570,19 - Unable to download High_Poly_Head_v1.4_(SE).zip (VectorPlexusOAuthDownloader+State|283|High_Poly_Head_v1.4_(SE).zip|False)
570,19 - Unable to download Data_Dawnguard.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\dawnguard.esm)
570,19 - Unable to download Data_Dragonborn.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\dragonborn.esm)
570,19 - Unable to download Data_HearthFires.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\hearthfires.esm)
570,19 - Unable to download Data_Update.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\update.esm)
570,19 - Unable to download TUDM - The Ultimate Dodge Mod v4 x64.rar (GoogleDriveDownloader+State|0B2VgBVA9jE6RTjJiYnRTTE9qRUE)
570,19 - Unable to download Data_Skyrim - Animations.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - animations.bsa)
570,19 - Unable to download Data_Skyrim - Interface.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - interface.bsa)
570,19 - Unable to download Data_Skyrim - Meshes0.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - meshes0.bsa)
570,19 - Unable to download Data_Skyrim - Meshes1.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - meshes1.bsa)
570,19 - Unable to download Data_Skyrim - Misc.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - misc.bsa)
570,19 - Unable to download Data_Skyrim - Patch.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - patch.bsa)
570,19 - Unable to download Data_Skyrim - Shaders.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - shaders.bsa)
570,19 - Unable to download Data_Skyrim - Sounds.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - sounds.bsa)
570,19 - Unable to download Data_Skyrim.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim.esm)
570,19 - Unable to download Data_Skyrim - Textures3.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - textures3.bsa)
570,19 - Unable to download Data_Skyrim - Textures0.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - textures0.bsa)
570,19 - Cannot continue, was unable to download one or more archives
570,19 - File hash check (-42) 601ae8a7754a68199d625bee07b7f0e9722ab6f4a3d223372e4913783c394b9e
570,27 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
   570,43 - File hash check (-42) 601ae8a7754a68199d625bee07b7f0e9722ab6f4a3d223372e4913783c394b9e


got this error maybe its because skyrim got a newer update Skyrim ist not on version 1.5.97.0 anymore its now 1.6.318

**Comment by CroniC-** [comment]
Same Problem here 

<details>
  <summary>Log File - Click to expand</summary>
1348,86 - Loading ModLists from GitHub
1357,41 - Starting to install Elysium
1357,43 - Starting Installer Task
1357,43 - Installation has Started
1357,43 - File hash check (-42) 7eb5c6b5e5a9f982cd8d6401f2272db2c8ce63ce43e4d54ea4ee31cec68a28bf
1357,72 - Configuring Processor
1357,72 - Install Folder: E:\elysium
1357,72 - Downloads Folder: E:\elysium\downloads
1357,72 - Game Folder: E:\Games\Steam\steamapps\common\Skyrim Special Edition
1357,72 - Wabbajack Folder: E:\wabbajack\2.5.3.1
1357,72 - Drive watcher is starting. Will warn at 8GB and error at 4GB
1357,72 - Starting Drive watcher on E:\ currently 312,8GB free out of 465,7GB
1357,72 - Validating Game ESMs
1357,73 - Creating Output Folders
1357,78 - Optimizing ModList
1357,78 - Optimizing ModList directives
1360,92 - Looking for files to delete
1360,93 - Cleaning empty folders
1361,99 - Looking for unmodified files
1362,55 - Updating ModList
1362,55 - Optimized 241594 directives to 241594 required
1362,61 - Hashing Archives
1362,61 - Looking for files to hash
1362,69 - Found 1601 total files, 1531 matching filesize
1362,86 - Downloading Missing Archives
1362,86 - Missing 20 archives
1362,86 - Getting Nexus API Key, if a browser appears, please accept
1362,86 - Loading server whitelist
1362,91 - Loaded permissions for 580 servers and 263 Google Drive files
1362,91 - File hash check (-42) 7eb5c6b5e5a9f982cd8d6401f2272db2c8ce63ce43e4d54ea4ee31cec68a28bf
1362,92 - Downloading Data_Skyrim - Misc.bsa
1362,92 - Downloading Data_Skyrim - Animations.bsa
1362,92 - Downloading Skyrim 2020 8.4.2 - 2K-2347-8-4-2-1623772523.7z
1362,92 - Downloading Data_Skyrim - Textures3.bsa
1362,93 - Downloading Data_Skyrim - Patch.bsa
1362,93 - Downloading Data_Skyrim - Sounds.bsa
1362,93 - Downloading Data_Skyrim - Shaders.bsa
1362,93 - Downloading Data_Update.esm
1362,93 - Downloading Data_Skyrim.esm
1362,93 - Downloading Data_Skyrim - Interface.bsa
1362,93 - Downloading Data_Skyrim - Meshes1.bsa
1362,93 - Downloading Data_Skyrim - Textures0.bsa
1362,93 - Downloading Data_Skyrim - Meshes0.bsa
1362,93 - Downloading TUDM - The Ultimate Dodge Mod v4 x64.rar
1362,93 - Downloading Data_HearthFires.esm
1362,94 - (Retry 1 of 5), got exception (2) Das System kann die angegebene Datei nicht finden: [E:\Games\Steam\steamapps\common\Skyrim Special Edition\Data\Skyrim - Patch.bsa], waiting 100ms
1363,05 - (Retry 2 of 5), got exception (2) Das System kann die angegebene Datei nicht finden: [E:\Games\Steam\steamapps\common\Skyrim Special Edition\Data\Skyrim - Patch.bsa], waiting 200ms
1363,06 - Hashed download is incorrect
1363,06 - Loading for alternative to GPdcQrqi2NI=
1363,19 - File hash check (-42) 7eb5c6b5e5a9f982cd8d6401f2272db2c8ce63ce43e4d54ea4ee31cec68a28bf
1363,2 - No alternative for GPdcQrqi2NI= could be found
1363,26 - (Retry 3 of 5), got exception (2) Das System kann die angegebene Datei nicht finden: [E:\Games\Steam\steamapps\common\Skyrim Special Edition\Data\Skyrim - Patch.bsa], waiting 400ms
1363,26 - Hashed download is incorrect
1363,26 - Loading for alternative to /DLG/LjdGXI=
1363,3 - No alternative for /DLG/LjdGXI= could be found
1363,46 - File hash check (-42) 7eb5c6b5e5a9f982cd8d6401f2272db2c8ce63ce43e4d54ea4ee31cec68a28bf
1363,67 - (Retry 4 of 5), got exception (2) Das System kann die angegebene Datei nicht finden: [E:\Games\Steam\steamapps\common\Skyrim Special Edition\Data\Skyrim - Patch.bsa], waiting 800ms
1363,81 - Hashed download is incorrect
1363,81 - Loading for alternative to kX9UFltG4+s=
1363,92 - Hashed download is incorrect
1363,92 - Loading for alternative to yRcX3Ttf9YM=
1363,95 - No alternative for kX9UFltG4+s= could be found
1364,07 - No alternative for yRcX3Ttf9YM= could be found
1364,17 - Hashed download is incorrect
1364,17 - Loading for alternative to k5EWx/9Woqg=
1364,33 - No alternative for k5EWx/9Woqg= could be found
1364,42 - Hashed download is incorrect
1364,42 - Loading for alternative to U659DN1scQM=
1364,48 - (Retry 5 of 5), got exception (2) Das System kann die angegebene Datei nicht finden: [E:\Games\Steam\steamapps\common\Skyrim Special Edition\Data\Skyrim - Patch.bsa], waiting 1600ms
1364,57 - No alternative for U659DN1scQM= could be found
1365,16 - Hashed download is incorrect
1365,16 - Loading for alternative to /Sglpr+ZffA=
1365,28 - No alternative for /Sglpr+ZffA= could be found
1365,61 - Hashed download is incorrect
1365,61 - Loading for alternative to krNnq2qHmOo=
1365,76 - No alternative for krNnq2qHmOo= could be found
1365,76 - Downloading Data_Dragonborn.esm
1366,09 - Loading for alternative to GG4pOfUmiRA=
1366,15 - No alternative for GG4pOfUmiRA= could be found
1366,15 - Downloading Data_Dawnguard.esm
1366,65 - Hashed download is incorrect
1366,65 - Loading for alternative to CEgEhUUtOcU=
1366,74 - No alternative for CEgEhUUtOcU= could be found
1366,74 - Downloading SkyrimSE.exe
1366,79 - Hashed download is incorrect
1366,79 - Loading for alternative to eN9rU4PSvEs=
1366,82 - No alternative for eN9rU4PSvEs= could be found
1366,82 - Downloading Skyrim.ccc
1366,82 - Hashed download is incorrect
1366,82 - Loading for alternative to yLhCbCSfkuE=
1366,86 - No alternative for yLhCbCSfkuE= could be found
1366,86 - Downloading binkw64.dll
1366,86 - (Retry 1 of 5), got exception (2) Das System kann die angegebene Datei nicht finden: [E:\Games\Steam\steamapps\common\Skyrim Special Edition\binkw64.dll], waiting 100ms
1366,94 - Hashed download is incorrect
1366,94 - Loading for alternative to eypuUwdQUb4=
1366,97 - (Retry 2 of 5), got exception (2) Das System kann die angegebene Datei nicht finden: [E:\Games\Steam\steamapps\common\Skyrim Special Edition\binkw64.dll], waiting 200ms
1367,05 - No alternative for eypuUwdQUb4= could be found
1367,17 - (Retry 3 of 5), got exception (2) Das System kann die angegebene Datei nicht finden: [E:\Games\Steam\steamapps\common\Skyrim Special Edition\binkw64.dll], waiting 400ms
1367,3 - Hashed download is incorrect
1367,3 - Loading for alternative to 8iPX1dhv7+E=
1367,38 - No alternative for 8iPX1dhv7+E= could be found
1367,58 - (Retry 4 of 5), got exception (2) Das System kann die angegebene Datei nicht finden: [E:\Games\Steam\steamapps\common\Skyrim Special Edition\binkw64.dll], waiting 800ms
1368,39 - (Retry 5 of 5), got exception (2) Das System kann die angegebene Datei nicht finden: [E:\Games\Steam\steamapps\common\Skyrim Special Edition\binkw64.dll], waiting 1600ms
1369,76 - Hashed download is incorrect
1369,76 - Loading for alternative to EwvbU7wcUUo=
1369,83 - No alternative for EwvbU7wcUUo= could be found
1370 - Loading for alternative to FZXovxp8lX0=
1370,05 - No alternative for FZXovxp8lX0= could be found
1377,35 - Hashed download is incorrect
1377,35 - Loading for alternative to XTaNNFIm3eM=
1377,41 - No alternative for XTaNNFIm3eM= could be found
1379,98 - Hashed download is incorrect
1379,98 - Loading for alternative to rENi4TDkFjY=
1380,04 - No alternative for rENi4TDkFjY= could be found
1380,88 - Hashed download is incorrect
1380,88 - Loading for alternative to 8LzXRU4x9Sw=
1380,95 - No alternative for 8LzXRU4x9Sw= could be found
1722,8 - Hashing Remaining Archives
1722,8 - Looking for files to hash
1722,87 - Found 1601 total files, 1532 matching filesize
1723,03 - Unable to download binkw64.dll (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|binkw64.dll)
1723,03 - Unable to download Skyrim.ccc (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|skyrim.ccc)
1723,03 - Unable to download SkyrimSE.exe (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|skyrimse.exe)
1723,03 - Unable to download Data_Dawnguard.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\dawnguard.esm)
1723,03 - Unable to download Data_Dragonborn.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\dragonborn.esm)
1723,03 - Unable to download Data_HearthFires.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\hearthfires.esm)
1723,03 - Unable to download Data_Update.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\update.esm)
1723,03 - Unable to download TUDM - The Ultimate Dodge Mod v4 x64.rar (GoogleDriveDownloader+State|0B2VgBVA9jE6RTjJiYnRTTE9qRUE)
1723,03 - Unable to download Data_Skyrim - Animations.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - animations.bsa)
1723,03 - Unable to download Data_Skyrim - Interface.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - interface.bsa)
1723,03 - Unable to download Data_Skyrim - Meshes0.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - meshes0.bsa)
1723,03 - Unable to download Data_Skyrim - Meshes1.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - meshes1.bsa)
1723,03 - Unable to download Data_Skyrim - Misc.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - misc.bsa)
1723,03 - Unable to download Data_Skyrim - Patch.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - patch.bsa)
1723,03 - Unable to download Data_Skyrim - Shaders.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - shaders.bsa)
1723,03 - Unable to download Data_Skyrim - Sounds.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - sounds.bsa)
1723,03 - Unable to download Data_Skyrim.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim.esm)
1723,03 - Unable to download Data_Skyrim - Textures3.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - textures3.bsa)
1723,03 - Unable to download Data_Skyrim - Textures0.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - textures0.bsa)
1723,03 - Cannot continue, was unable to download one or more archives
1723,04 - File hash check (-42) 7eb5c6b5e5a9f982cd8d6401f2272db2c8ce63ce43e4d54ea4ee31cec68a28bf
1723,04 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
1723,39 - File hash check (-42) 7eb5c6b5e5a9f982cd8d6401f2272db2c8ce63ce43e4d54ea4ee31cec68a28bf

</details>

**Comment by motte49** [comment]
You need to downgrade Skyrim with https://www.nexusmods.com/skyrimspecialedition/mods/57618
then it work

**Comment by CroniC-** [comment]
Thank you for the link. After reinstall and downgrade unfortunately i'm getting another error.
It's not the same and the log is way shorter.

Version is 1.5.97

<details>
  <summary>Log File - Click to expand</summary>

> 0,19 - Wabbajack Build - fed371a6f1956ee74801c18be22a6d628c68bc0f
0,19 - Running in E:\wabbajack\2.5.3.1
0,2 - Detected Windows Version: 10.0.19043.0
0,2 - System settings - (31,9GB RAM) (4,8GB Page), Display: 2560 x 1440 (8GB VRAM - VideoMemorySizeMb=10240)
0,2 - Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance.
0,21 - Getting new Wabbajack version list
0,23 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "E:\Games\Steam\steamapps\common\Skyrim Special Edition"
0,5 - Wabbajack Version: 2.5.3.1
1,17 - Build server is alive
1,17 - File hash check (-42) 7eb5c6b5e5a9f982cd8d6401f2272db2c8ce63ce43e4d54ea4ee31cec68a28bf
1,58 - Build server is alive
1,58 - File hash check (-42) 7eb5c6b5e5a9f982cd8d6401f2272db2c8ce63ce43e4d54ea4ee31cec68a28bf
2,09 - Loading ModLists from GitHub
20,54 - Starting to install Elysium
20,55 - Cleaning VFS, this may take a bit of time
20,59 - Starting Installer Task
20,59 - Installation has Started
20,59 - File hash check (-42) 7eb5c6b5e5a9f982cd8d6401f2272db2c8ce63ce43e4d54ea4ee31cec68a28bf
20,84 - Configuring Processor
20,85 - Install Folder: E:\elysium
20,85 - Downloads Folder: E:\elysium\downloads
20,85 - Game Folder: E:\Games\Steam\steamapps\common\Skyrim Special Edition
20,86 - Wabbajack Folder: E:\wabbajack\2.5.3.1
20,86 - Drive watcher is starting. Will warn at 8GB and error at 4GB
20,86 - Starting Drive watcher on E:\ currently 307,6GB free out of 465,7GB
20,86 - Validating Game ESMs
20,88 - Creating Output Folders
21,51 - Optimizing ModList
21,51 - Optimizing ModList directives
24,74 - Looking for files to delete
24,81 - Cleaning empty folders
25,84 - Looking for unmodified files
26,32 - Updating ModList
26,32 - Optimized 241594 directives to 241594 required
26,41 - Hashing Archives
26,41 - Looking for files to hash
26,48 - Found 1597 total files, 1550 matching filesize
63,99 - Downloading Missing Archives
63,99 - Missing 1 archives
63,99 - Getting Nexus API Key, if a browser appears, please accept
64 - Loading server whitelist
64,08 - Loaded permissions for 580 servers and 263 Google Drive files
64,08 - File hash check (-42) 7eb5c6b5e5a9f982cd8d6401f2272db2c8ce63ce43e4d54ea4ee31cec68a28bf
64,09 - Downloading TUDM - The Ultimate Dodge Mod v4 x64.rar
65,31 - Hashed download is incorrect
65,31 - Loading for alternative to U659DN1scQM=
65,36 - No alternative for U659DN1scQM= could be found
65,39 - Hashing Remaining Archives
65,39 - Looking for files to hash
65,46 - Found 1597 total files, 1550 matching filesize
65,63 - Unable to download TUDM - The Ultimate Dodge Mod v4 x64.rar (GoogleDriveDownloader+State|0B2VgBVA9jE6RTjJiYnRTTE9qRUE)
65,63 - Cannot continue, was unable to download one or more archives
65,63 - File hash check (-42) 7eb5c6b5e5a9f982cd8d6401f2272db2c8ce63ce43e4d54ea4ee31cec68a28bf
65,67 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
65,91 - File hash check (-42) 7eb5c6b5e5a9f982cd8d6401f2272db2c8ce63ce43e4d54ea4ee31cec68a28bf
</details>

**Comment by YoungWhitey** [comment]
did you download full patcher or best of both worlds patcher?

**Comment by CroniC-** [comment]
> 
> 
> did you download full patcher or best of both worlds patcher?

First the bothworldspatcher - but this one didn't work correctly without giving any error. Quite confusing.
But the Full patcher worked fine.

**Comment by YoungWhitey** [comment]
Okay i have downloaded the Full Patcher, much appreciated :)

**Comment by motte49** [comment]
Full patcher worked for me
