### ISSUE TITLE
Dragonsreach Great Porch DyndoLOD error

### ISSUE THREAD

**Issue by holt100** [TitansBane/Elysium#22]
Screenshot below shows the issue on the Great Porch.
Doesn't actually cause a crash in my experience, but the message keeps repeating every few seconds.  Might be an install issue on my end, but it's minor enough that I don't feel like testing via reinstalling/troubleshooting mid playthrough.  

![ScreenShot0](https://user-images.githubusercontent.com/75289926/102959179-d5628780-44ac-11eb-9837-1d4cb450e93d.png)

**Comment by electraumatized** [comment]
Can confirm this issue on 2.6.2 as well

**Comment by TitansBane** [comment]
An issue with the current Dyndolod version that Elysium is using for grass LODs. Nothing game-breaking, though.
