### ISSUE TITLE
Istallation failed by hashing the files

### ISSUE THREAD

**Issue by nitecrow21** [TitansBane/Elysium#222]
Hi There

my installation failed on hashing the files.
please help me

current log is here:

0,17 - Wabbajack Build - fed371a6f1956ee74801c18be22a6d628c68bc0f
0,18 - Running in E:\Wabbajack\2.5.3.1
0,18 - Detected Windows Version: 10.0.19042.0
0,18 - System settings - (31,9GB RAM) (4,8GB Page), Display: 1920 x 1080 (7,9GB VRAM - VideoMemorySizeMb=10240)
0,18 - Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance.
0,19 - Getting new Wabbajack version list
0,2 - Steam: Found no Regex matches in Steam Config at e:/steam\config\config.vdf
0,2 - Steam: Found game New World (1063730) at "E:\Steam\steamapps\common\New World"
0,2 - Steam: Found game Steamworks Common Redistributables (228980) at "E:\Steam\steamapps\common\Steamworks Shared"
0,2 - Steam: Found game Grand Theft Auto V (271590) at "E:\Steam\steamapps\common\Grand Theft Auto V"
0,2 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "E:\Steam\steamapps\common\Skyrim Special Edition"
0,2 - Steam: Found game New World (1063730) at "e:/steam\steamapps\common\New World"
0,2 - Steam: Found game Steamworks Common Redistributables (228980) at "e:/steam\steamapps\common\Steamworks Shared"
0,2 - Steam: Found game Grand Theft Auto V (271590) at "e:/steam\steamapps\common\Grand Theft Auto V"
0,2 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "e:/steam\steamapps\common\Skyrim Special Edition"
0,2 - GOG: GOG was not found in the registry
0,21 - BethNet: Found game Creation Kit: Skyrim (10) at "E:\Steam\steamapps\common\Skyrim Special Edition"
0,21 - EGS: Unable to open Registry Key SOFTWARE\Epic Games\EOS
0,21 - Origin: LocalContent directory at C:\ProgramData\Origin\LocalContent does not exist
0,63 - Wabbajack Version: 2.5.3.1
0,92 - Build server is alive
0,92 - File hash check (-42) 29c05d94646d13cb11cd9f5988ad5914c8ba9b42c8287ed97f1a32ad195fe4bb
1,37 - Build server is alive
1,37 - File hash check (-42) 29c05d94646d13cb11cd9f5988ad5914c8ba9b42c8287ed97f1a32ad195fe4bb
7,59 - Starting to install Elysium
7,6 - Cleaning VFS, this may take a bit of time
7,63 - Starting Installer Task
7,63 - Installation has Started
7,63 - File hash check (-42) 29c05d94646d13cb11cd9f5988ad5914c8ba9b42c8287ed97f1a32ad195fe4bb
8,35 - Configuring Processor
8,35 - Install Folder: E:\Elysium
8,35 - Downloads Folder: E:\Elysium\downloads
8,35 - Game Folder: E:\Steam\steamapps\common\Skyrim Special Edition
8,35 - Wabbajack Folder: E:\Wabbajack\2.5.3.1
8,35 - Drive watcher is starting. Will warn at 8GB and error at 4GB
8,36 - Starting Drive watcher on E:\ currently 87,7GB free out of 465,8GB
8,36 - Validating Game ESMs
8,37 - Creating Output Folders
8,44 - Optimizing ModList
8,44 - Optimizing ModList directives
10,63 - Looking for files to delete
10,65 - Cleaning empty folders
11,37 - Looking for unmodified files
11,7 - Updating ModList
11,71 - Optimized 241594 directives to 241594 required
11,76 - Hashing Archives
11,76 - Looking for files to hash
12,06 - Found 11158 total files, 1839 matching filesize
12,21 - Downloading Missing Archives
12,21 - Missing 13 archives
12,21 - Getting Nexus API Key, if a browser appears, please accept
12,22 - Loading server whitelist
12,29 - Loaded permissions for 580 servers and 263 Google Drive files
12,29 - File hash check (-42) 29c05d94646d13cb11cd9f5988ad5914c8ba9b42c8287ed97f1a32ad195fe4bb
12,4 - Downloading Data_Skyrim - Meshes0.bsa
12,4 - Downloading TUDM - The Ultimate Dodge Mod v4 x64.rar
12,4 - Downloading Data_Skyrim - Sounds.bsa
12,4 - Downloading Data_Update.esm
12,4 - Downloading Data_Skyrim - Textures3.bsa
12,4 - Downloading Data_Skyrim - Textures0.bsa
12,4 - Downloading Data_Skyrim - Misc.bsa
12,4 - Downloading Data_Skyrim - Meshes1.bsa
12,4 - Downloading Data_Skyrim - Shaders.bsa
12,4 - Downloading Data_Skyrim - Patch.bsa
12,4 - Downloading Skyrim_Default.ini
12,4 - Downloading Data_Skyrim.esm
12,4 - Downloading Data_Skyrim - Interface.bsa
12,4 - (Retry 1 of 5), got exception (2) Das System kann die angegebene Datei nicht finden: [E:\Steam\steamapps\common\Skyrim Special Edition\Data\Skyrim - Patch.bsa], waiting 100ms
12,5 - (Retry 2 of 5), got exception (2) Das System kann die angegebene Datei nicht finden: [E:\Steam\steamapps\common\Skyrim Special Edition\Data\Skyrim - Patch.bsa], waiting 200ms
12,53 - File hash check (-42) 29c05d94646d13cb11cd9f5988ad5914c8ba9b42c8287ed97f1a32ad195fe4bb
12,58 - Hashed download is incorrect
12,58 - Loading for alternative to JbYP1w8FSfY=
12,64 - No alternative for JbYP1w8FSfY= could be found
12,71 - (Retry 3 of 5), got exception (2) Das System kann die angegebene Datei nicht finden: [E:\Steam\steamapps\common\Skyrim Special Edition\Data\Skyrim - Patch.bsa], waiting 400ms
12,85 - Hashed download is incorrect
12,85 - Loading for alternative to /DLG/LjdGXI=
12,89 - No alternative for /DLG/LjdGXI= could be found
13,12 - (Retry 4 of 5), got exception (2) Das System kann die angegebene Datei nicht finden: [E:\Steam\steamapps\common\Skyrim Special Edition\Data\Skyrim - Patch.bsa], waiting 800ms
13,47 - Hashed download is incorrect
13,47 - Loading for alternative to U659DN1scQM=
13,5 - No alternative for U659DN1scQM= could be found
13,54 - Hashed download is incorrect
13,54 - Loading for alternative to k5EWx/9Woqg=
13,56 - No alternative for k5EWx/9Woqg= could be found
13,58 - Hashed download is incorrect
13,58 - Loading for alternative to yRcX3Ttf9YM=
13,6 - No alternative for yRcX3Ttf9YM= could be found
13,92 - (Retry 5 of 5), got exception (2) Das System kann die angegebene Datei nicht finden: [E:\Steam\steamapps\common\Skyrim Special Edition\Data\Skyrim - Patch.bsa], waiting 1600ms
14,45 - Hashed download is incorrect
14,46 - Loading for alternative to /Sglpr+ZffA=
14,49 - No alternative for /Sglpr+ZffA= could be found
14,75 - Hashed download is incorrect
14,75 - Loading for alternative to krNnq2qHmOo=
14,79 - No alternative for krNnq2qHmOo= could be found
15,46 - Hashed download is incorrect
15,46 - Loading for alternative to eN9rU4PSvEs=
15,5 - No alternative for eN9rU4PSvEs= could be found
15,54 - Loading for alternative to GG4pOfUmiRA=
15,55 - No alternative for GG4pOfUmiRA= could be found
16,99 - Hashed download is incorrect
16,99 - Loading for alternative to EwvbU7wcUUo=
17,02 - No alternative for EwvbU7wcUUo= could be found
24,02 - Hashed download is incorrect
24,02 - Loading for alternative to XTaNNFIm3eM=
24,06 - No alternative for XTaNNFIm3eM= could be found
27,62 - Hashed download is incorrect
27,62 - Loading for alternative to rENi4TDkFjY=
27,65 - No alternative for rENi4TDkFjY= could be found
28,6 - Hashed download is incorrect
28,6 - Loading for alternative to 8LzXRU4x9Sw=
28,64 - No alternative for 8LzXRU4x9Sw= could be found
28,69 - Hashing Remaining Archives
28,69 - Looking for files to hash
29 - Found 11158 total files, 1839 matching filesize
29,11 - Unable to download Skyrim_Default.ini (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|skyrim_default.ini)
29,11 - Unable to download Data_Update.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\update.esm)
29,11 - Unable to download TUDM - The Ultimate Dodge Mod v4 x64.rar (GoogleDriveDownloader+State|0B2VgBVA9jE6RTjJiYnRTTE9qRUE)
29,11 - Unable to download Data_Skyrim - Interface.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - interface.bsa)
29,11 - Unable to download Data_Skyrim - Meshes0.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - meshes0.bsa)
29,11 - Unable to download Data_Skyrim - Meshes1.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - meshes1.bsa)
29,11 - Unable to download Data_Skyrim - Misc.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - misc.bsa)
29,11 - Unable to download Data_Skyrim - Patch.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - patch.bsa)
29,11 - Unable to download Data_Skyrim - Shaders.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - shaders.bsa)
29,11 - Unable to download Data_Skyrim - Sounds.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - sounds.bsa)
29,11 - Unable to download Data_Skyrim.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim.esm)
29,11 - Unable to download Data_Skyrim - Textures3.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - textures3.bsa)
29,11 - Unable to download Data_Skyrim - Textures0.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - textures0.bsa)
29,11 - Cannot continue, was unable to download one or more archives
29,11 - File hash check (-42) 29c05d94646d13cb11cd9f5988ad5914c8ba9b42c8287ed97f1a32ad195fe4bb
29,12 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
29,58 - File hash check (-42) 29c05d94646d13cb11cd9f5988ad5914c8ba9b42c8287ed97f1a32ad195fe4bb

**Comment by CroniC-** [comment]
This Problem is solved in this Thread:

https://github.com/TitansBane/Elysium/issues/219
