### ISSUE TITLE
Installation Failed every time

### ISSUE THREAD

**Issue by EDDIE2Fast** [TitansBane/Elysium#223]
Hello together,

my installation Failed every Time.
Ich check and solved the "The Ultimate Dodge Mod" Fix and i use the "Unofficial Skyrim Special Edition Downgrade Patcher". 
Now i am stuck @ the log error below.

185,06 - Done downloading elysium
185,06 - Done hashing elysium
246,69 - Starting to install Elysium
246,7 - Cleaning VFS, this may take a bit of time
246,73 - Starting Installer Task
246,73 - Installation has Started
246,73 - File hash check (-42) a88fa7087a6c4d750e60bf8cecd5f74b97c7c5ba95e5a85f563de4e5d66ba817
247,3 - Configuring Processor
247,31 - Install Folder: I:\Wabberjack
247,31 - Downloads Folder: E:\Wabbaajack Downloads
247,31 - Game Folder: I:\SteamLibrary\steamapps\common\Skyrim Special Edition
247,31 - Wabbajack Folder: C:\Skyrim Wabbaajack
247,31 - Drive watcher is starting. Will warn at 8GB and error at 4GB
247,31 - Starting Drive watcher on I:\ currently 223,2GB free out of 931,5GB
247,31 - Starting Drive watcher on E:\ currently 768,8GB free out of 1,8TB
247,31 - Starting Drive watcher on C:\ currently 21,6GB free out of 237,9GB
247,31 - Validating Game ESMs
247,32 - Creating Output Folders
247,42 - Optimizing ModList
247,42 - Optimizing ModList directives
249,83 - Looking for files to delete
249,83 - Cleaning empty folders
250,54 - Looking for unmodified files
251,5 - Updating ModList
251,5 - Optimized 241594 directives to 241594 required
251,55 - Hashing Archives
251,55 - Looking for files to hash
251,63 - Found 1834 total files, 1556 matching filesize
251,91 - Downloading Missing Archives
251,91 - Missing 1 archives
251,91 - Getting Nexus API Key, if a browser appears, please accept
251,91 - Loading server whitelist
251,99 - Loaded permissions for 582 servers and 263 Google Drive files
251,99 - File hash check (-42) a88fa7087a6c4d750e60bf8cecd5f74b97c7c5ba95e5a85f563de4e5d66ba817
252,01 - Downloading Skyrim_Default.ini
252,03 - Hashed download is incorrect
252,03 - Loading for alternative to JbYP1w8FSfY=
252,04 - No alternative for JbYP1w8FSfY= could be found
252,09 - Hashing Remaining Archives
252,09 - Looking for files to hash
252,17 - Found 1834 total files, 1556 matching filesize
252,43 - Unable to download Skyrim_Default.ini (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|skyrim_default.ini)
252,43 - Cannot continue, was unable to download one or more archives
252,43 - File hash check (-42) a88fa7087a6c4d750e60bf8cecd5f74b97c7c5ba95e5a85f563de4e5d66ba817
252,45 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
252,98 - File hash check (-42) a88fa7087a6c4d750e60bf8cecd5f74b97c7c5ba95e5a85f563de4e5d66ba817

**Comment by motte49** [comment]
You have the settings from the game in english?? when not change to english in steam

**Comment by EDDIE2Fast** [comment]
Hy @motte49 thank you so mutch. Your tip is working finde for me. Thank you
