### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Necro87** [TitansBane/Elysium#225]
i keep having weird crashes and stutters that i dont know the cause of.. i have disabled the following:

Quick Loot RE
QuickLoot Retexture
More Immersive Activations
Immersive Lockpicking

changed 
Improved camera custom to no head-bob version 
Texgen output preformance mode
Dyndolod 3d Output preformance mode

and enabled
No Grass in objects - preformance mode
[Crash_2021_11_17_19-4-37.txt](https://github.com/TitansBane/Elysium/files/7556990/Crash_2021_11_17_19-4-37.txt)
.

any ideas?

**Comment by Taylorsd** [comment]
was it crashing before changing any of the original plugins?  There's no issue with the camera or texgen, Dyndolod , or the No Grass. Unless maybe you have the other Texgen and Dyndolod options still enabled. 
Quick Loot  I have disabled midgame with no issues myself. 

The ones with animations however might be an issue. Might be still loaded in memory if you disabled them midgame.  Immersive Interactions was ran through Nemesis to configure the animations, if the plugin is disabled then game might still be looking for them. Running Nemesis Engine Update and then the Nemesis Behavior might fix this. Or, I would simply load the plugin back and disable the animations through the MCM

**Comment by Necro87** [comment]
iv re enabled more immersive activations and disabled it in the mcm insted.. ill update after having run it abit like this to see if crash issue fixed or not.

**Comment by Necro87** [comment]
crash seems to be fixed now, and some minor stutter i had is also gone after i changed [Papyrus] in the ini back to default stuff.
