### ISSUE TITLE
Elysium Won't install

### ISSUE THREAD

**Issue by TurtleHD** [TitansBane/Elysium#229]
Wabbajack keeps failing to find my skyrim game folder so it is unable to copy the files. Everything is updated, game files have been validated in steam and I can launch and run skyrim no problem. Not sure why Wabbajack is having these issues. Here is the log below.

0.2 - Wabbajack Build - fed371a6f1956ee74801c18be22a6d628c68bc0f
0.22 - Running in D:\Wabbajack\2.5.3.1
0.23 - Detected Windows Version: 10.0.19042.0
0.23 - System settings - (15.9GB RAM) (10.3GB Page), Display: 1920 x 1080 (7.9GB VRAM - VideoMemorySizeMb=10240)
0.23 - Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance.
0.24 - Steam: Found no Regex matches in Steam Config at c:/program files (x86)/steam\config\config.vdf
0.26 - Steam: Found game Fireworks Mania (1079260) at "D:\Steam\steamapps\common\Fireworks Mania"
0.26 - Steam: Found game Persona 4 Golden (1113000) at "D:\Steam\steamapps\common\Persona 4 Golden"
0.26 - Steam: Found game PlanetSide 2 (218230) at "D:\Steam\steamapps\common\PlanetSide 2"
0.26 - Steam: Found game The Elder Scrolls IV: Oblivion  (22330) at "D:\Steam\steamapps\common\Oblivion"
0.26 - Steam: Found game Fallout: New Vegas (22380) at "D:\Steam\steamapps\common\Fallout New Vegas"
0.26 - Steam: Found game Steamworks Common Redistributables (228980) at "D:\Steam\steamapps\common\Steamworks Shared"
0.26 - Steam: Found game The Legend of Heroes: Trails in the Sky (251150) at "D:\Steam\steamapps\common\Trails in the Sky FC"
0.26 - Steam: Found game iRacing (266410) at "D:\Steam\steamapps\common\iRacing"
0.26 - Steam: Found game BeamNG.drive (284160) at "D:\Steam\steamapps\common\BeamNG.drive"
0.26 - Steam: Found game The Witcher 3: Wild Hunt (292030) at "D:\Steam\steamapps\common\The Witcher 3"
0.26 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "D:\Steam\steamapps\common\Skyrim Special Edition"
0.26 - Steam: Found game Monster Hunter: World (582010) at "D:\Steam\steamapps\common\Monster Hunter World"
0.26 - Steam: Found game Okami HD (587620) at "D:\Steam\steamapps\common\Okami"
0.26 - Steam: Found game Journey (638230) at "D:\Steam\steamapps\common\Journey"
0.26 - Steam: Found game CODE VEIN (678960) at "D:\Steam\steamapps\common\CODE VEIN"
0.27 - Steam: Found game Flower (966330) at "D:\Steam\steamapps\common\Flower"
0.27 - GOG: GOG was not found in the registry
0.27 - BethNet: Unable to open Registry Keys SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net and SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net
0.27 - EGS: Unable to open Registry Key SOFTWARE\Epic Games\EOS
0.27 - Origin: LocalContent directory at C:\ProgramData\Origin\LocalContent does not exist
1.46 - Getting new Wabbajack version list
1.77 - Wabbajack Version: 2.5.3.1
1.95 - Build server is alive
1.95 - File hash check (-42) d542efed6b72f5952065baea578830c22bb99fe9477a51e95d76e2b67aabbed2
1.96 - Build server is alive
1.96 - File hash check (-42) d542efed6b72f5952065baea578830c22bb99fe9477a51e95d76e2b67aabbed2
3.46 - Loading ModLists from GitHub
15.06 - Starting to install Elysium
15.07 - Cleaning VFS, this may take a bit of time
15.15 - Starting Installer Task
15.15 - Installation has Started
15.15 - File hash check (-42) d542efed6b72f5952065baea578830c22bb99fe9477a51e95d76e2b67aabbed2
15.27 - Configuring Processor
15.28 - Install Folder: D:\Elysium
15.28 - Downloads Folder: D:\Elysium\downloads
15.28 - Game Folder: D:\Steam\steamapps\common\Skyrim Special Edition
15.28 - Wabbajack Folder: D:\Wabbajack\2.5.3.1
15.28 - Drive watcher is starting. Will warn at 8GB and error at 4GB
15.28 - Starting Drive watcher on D:\ currently 1.2TB free out of 1.8TB
15.28 - Validating Game ESMs
15.3 - Creating Output Folders
15.98 - Optimizing ModList
15.98 - Optimizing ModList directives
18.75 - Looking for files to delete
18.82 - Cleaning empty folders
19.88 - Looking for unmodified files
21.76 - Updating ModList
21.76 - Optimized 241594 directives to 241594 required
21.81 - Hashing Archives
21.81 - Looking for files to hash
21.88 - Found 1622 total files, 1531 matching filesize
64.96 - Downloading Missing Archives
64.96 - Missing 27 archives
64.96 - Getting Nexus API Key, if a browser appears, please accept
65.66 - Logged into the nexus as AlexLandry13
65.66 - Nexus calls remaining: 10000 daily, 500 hourly
65.85 - Logged into the nexus as AlexLandry13
65.86 - Nexus calls remaining: 10000 daily, 500 hourly
65.86 - Loading server whitelist
66.04 - Loaded permissions for 588 servers and 266 Google Drive files
66.04 - File hash check (-42) d542efed6b72f5952065baea578830c22bb99fe9477a51e95d76e2b67aabbed2
66.05 - Downloading Data_Skyrim - Textures3.bsa
66.05 - Downloading Data_Skyrim - Sounds.bsa
66.05 - Downloading Data_Skyrim - Patch.bsa
66.05 - Downloading Data_Skyrim.esm
66.05 - Downloading Data_Skyrim - Misc.bsa
66.05 - Downloading Data_Skyrim - Shaders.bsa
66.05 - Downloading Data_Skyrim - Textures0.bsa
66.07 - Downloading Data_Skyrim - Meshes1.bsa
66.15 - (Retry 1 of 5), got exception (2) The system cannot find the file specified: [D:\Steam\steamapps\common\Skyrim Special Edition\Data\Skyrim - Patch.bsa], waiting 100ms
66.26 - (Retry 2 of 5), got exception (2) The system cannot find the file specified: [D:\Steam\steamapps\common\Skyrim Special Edition\Data\Skyrim - Patch.bsa], waiting 200ms
66.3 - File hash check (-42) d542efed6b72f5952065baea578830c22bb99fe9477a51e95d76e2b67aabbed2
66.43 - File hash check (-42) d542efed6b72f5952065baea578830c22bb99fe9477a51e95d76e2b67aabbed2
66.46 - (Retry 3 of 5), got exception (2) The system cannot find the file specified: [D:\Steam\steamapps\common\Skyrim Special Edition\Data\Skyrim - Patch.bsa], waiting 400ms
66.7 - File hash check (-42) d542efed6b72f5952065baea578830c22bb99fe9477a51e95d76e2b67aabbed2
66.84 - File hash check (-42) d542efed6b72f5952065baea578830c22bb99fe9477a51e95d76e2b67aabbed2
66.86 - (Retry 4 of 5), got exception (2) The system cannot find the file specified: [D:\Steam\steamapps\common\Skyrim Special Edition\Data\Skyrim - Patch.bsa], waiting 800ms
67.68 - (Retry 5 of 5), got exception (2) The system cannot find the file specified: [D:\Steam\steamapps\common\Skyrim Special Edition\Data\Skyrim - Patch.bsa], waiting 1600ms
69.29 - Loading for alternative to GG4pOfUmiRA=
69.4 - No alternative for GG4pOfUmiRA= could be found
69.4 - Downloading Data_Skyrim - Meshes0.bsa
168.51 - Hashed download is incorrect
168.51 - Loading for alternative to yRcX3Ttf9YM=
168.59 - No alternative for yRcX3Ttf9YM= could be found
168.59 - Downloading Data_Skyrim - Interface.bsa
286.73 - Hashed download is incorrect
286.73 - Loading for alternative to k5EWx/9Woqg=
286.79 - No alternative for k5EWx/9Woqg= could be found
286.79 - Downloading Data_Skyrim - Animations.bsa
380.98 - Hashed download is incorrect
380.98 - Loading for alternative to /Sglpr+ZffA=
381.05 - No alternative for /Sglpr+ZffA= could be found
381.05 - Downloading TUDM - The Ultimate Dodge Mod v4 x64.rar
382.52 - Hashed download is incorrect
382.52 - Loading for alternative to U659DN1scQM=
382.71 - No alternative for U659DN1scQM= could be found
382.71 - Downloading Data_Update.esm
407.46 - Hashed download is incorrect
407.46 - Loading for alternative to kX9UFltG4+s=
407.52 - No alternative for kX9UFltG4+s= could be found
407.52 - Downloading Data_HearthFires.esm
416.61 - Hashed download is incorrect
416.61 - Loading for alternative to GPdcQrqi2NI=
416.66 - No alternative for GPdcQrqi2NI= could be found
416.67 - Downloading Data_Dragonborn.esm
416.73 - Hashed download is incorrect
416.74 - Loading for alternative to /DLG/LjdGXI=
416.75 - No alternative for /DLG/LjdGXI= could be found
416.75 - Downloading Data_Dawnguard.esm
455.68 - Hashed download is incorrect
455.68 - Loading for alternative to krNnq2qHmOo=
455.76 - No alternative for krNnq2qHmOo= could be found
455.76 - Downloading Elysium - Dyndolod 3D Output - Performance Mode.7z
458.51 - Hashed download is incorrect
458.51 - Loading for alternative to CEgEhUUtOcU=
470.74 - No alternative for CEgEhUUtOcU= could be found
470.74 - Downloading Elysium - Dyndolod 3D Output (Creation Club).7z
511.56 - Hashed download is incorrect
511.56 - Loading for alternative to eypuUwdQUb4=
511.63 - No alternative for eypuUwdQUb4= could be found
511.63 - Downloading Elysium - Dyndolod 3D Output.7z
651.88 - Hashed download is incorrect
651.88 - Loading for alternative to eN9rU4PSvEs=
651.94 - No alternative for eN9rU4PSvEs= could be found
651.94 - Downloading eFPS - Official Patch Hub-54998-1-5a-1635931350.zip
662.35 - Downloading Dynamic Cart Horses-40586-1-0-1600398408.7z
667.85 - Downloading Durnehviir Resurrected-14272-2-1.zip
696.17 - Downloading Basecoat - Textures only-46850-1-0-1615528651.7z
1062.81 - Downloading SkyrimSE.exe
1106.07 - Hashed download is incorrect
1106.07 - Loading for alternative to 8iPX1dhv7+E=
1106.21 - No alternative for 8iPX1dhv7+E= could be found
1106.21 - Downloading Skyrim.ccc
1106.39 - Hashed download is incorrect
1106.39 - Loading for alternative to yLhCbCSfkuE=
1106.48 - No alternative for yLhCbCSfkuE= could be found
1106.48 - Downloading Rudy ENB CW Zangdar's Edit ReShade preset.7z
1138.61 - Downloading binkw64.dll
1139.62 - (Retry 1 of 5), got exception (2) The system cannot find the file specified: [D:\Steam\steamapps\common\Skyrim Special Edition\binkw64.dll], waiting 100ms
1139.73 - (Retry 2 of 5), got exception (2) The system cannot find the file specified: [D:\Steam\steamapps\common\Skyrim Special Edition\binkw64.dll], waiting 200ms
1139.93 - (Retry 3 of 5), got exception (2) The system cannot find the file specified: [D:\Steam\steamapps\common\Skyrim Special Edition\binkw64.dll], waiting 400ms
1140.35 - (Retry 4 of 5), got exception (2) The system cannot find the file specified: [D:\Steam\steamapps\common\Skyrim Special Edition\binkw64.dll], waiting 800ms
1141.16 - (Retry 5 of 5), got exception (2) The system cannot find the file specified: [D:\Steam\steamapps\common\Skyrim Special Edition\binkw64.dll], waiting 1600ms
1142.77 - Loading for alternative to FZXovxp8lX0=
1142.86 - No alternative for FZXovxp8lX0= could be found
2335.57 - Hashed download is incorrect
2335.71 - Loading for alternative to EwvbU7wcUUo=
2362.58 - No alternative for EwvbU7wcUUo= could be found
2691.52 - Hashed download is incorrect
2691.52 - Loading for alternative to XTaNNFIm3eM=
2717.19 - No alternative for XTaNNFIm3eM= could be found
2819.05 - Hashed download is incorrect
2819.05 - Loading for alternative to rENi4TDkFjY=
2823.62 - Hashed download is incorrect
2823.62 - Loading for alternative to 8LzXRU4x9Sw=
2824.32 - No alternative for 8LzXRU4x9Sw= could be found
2870.62 - No alternative for rENi4TDkFjY= could be found
5354.39 - Loading for alternative to JJ2czF7SRlo=
5358.8 - No alternative for JJ2czF7SRlo= could be found
5404.28 - Loading for alternative to k6V+p1NaTWI=
5404.43 - No alternative for k6V+p1NaTWI= could be found

**Comment by Bambanah** [comment]
Elysium hasn't updated to the new version yet. You'll need to use the [AE Downgrade Patcher](https://www.nexusmods.com/skyrimspecialedition/mods/57618) to downgrade to the previous version.
