### ISSUE TITLE
Lockups in Snapleg Cave i.e. Skyrim not responding

### ISSUE THREAD

**Issue by researched** [TitansBane/Elysium#23]
I can enter the cave, but the game locks up (stops responding) when one shoot at the pink crystals (which blasts one from a distance). It's possible to dodge the crystal's blasts, but one still can't exit the cave. An either case, an End Task is required to quit the game and restart. Numerous attempts to work my way through the cave failed.

Oddity: No LOOT in Elysium? I can only presume that the sort order is specified by the author, and LOOT is therefore not required.

I disabled the few mods I added myself, but the problem persists. For interesting sake, these are the mods I used. I simply added them all to the bottom of the load order list:
* 360 Movement Behavior SE, because I like it to see my avatar from all direction even during fights.
* Asherz CBBE 4k Female Skin Replacer NUM 25 = the best CBBE skin in Skyrim, by far!
* CBP physics, because I love the jiggling.
* HDT-SMP (Skinned Mesh Physics) and KS Hairdos - HDT SMP (Physics) = moving hair
* 3rd person walk fix = more gradual turns instead of the usual instant "snap" when using the directional keys.
* ShowRaceMenu = has extra options to customize my avatar
* Player rotation in ShowRaceMenu = allows one to turn the avatar during showracemenu customization
* More Hotkeys Please SSE patch = solves map navigation issues. It's only installed, not configured in any way, which is enough to solve the map navigation issue.

But as mentioned, even disabling all of these extras, the "not responding" events still happens in Snapleg cave.

It would be amazing if you could check if you are encountering the same freezing problem in Snapleg cave, and fix it if possible, as the Solidor quests cannot continue unless one can find the first book in the Snapleg cave (and exit the cave with the book).

**Comment by researched** [comment]
Ha! And minutes later I stumbled upon a solution. Instead of shooting the pink crystal, I let the troll run up there and dislodge the crystal. There-after I could find the book and get out of the cave. It seems the issue occurs only if one either kill the troll (who will therefore not dislodge the crystal). Shoot the crystal with an arrow results in a freeze.

Simply running past the crystal (one dies a lot and must try it many times) prevents one from exiting the cave, as if a quest trigger is not getting checked.

Solution: the troll MUST dislodge the crystal, and then everything else seems to be working fine.

Would be great if this could be fixed in the game, as most will likely try to kill the troll on sight ... which will result in the mentioned issues.

**Comment by TitansBane** [comment]
Fixed for the next version.
