### ISSUE TITLE
Dyndolod 3d 3d output files won install.

### ISSUE THREAD

**Issue by TurtleHD** [TitansBane/Elysium#230]
I've tried restarting wabbajack 3 seperate times, but basically each time my dyndolod files will attempt to download. But then they will fail to hash. I have used the patcher to revert back SE.

**Comment by mathesoncd** [comment]
The dynolod files download from MEGA and are larger than the free filesize limit, so when you hit it wabbajack thinks it's done and moves on but then its not gonna hash because it's an incomplete file.

Had to get mega pro and link it in wabbajack to get it to download.
