### ISSUE TITLE
Unable to download TUDM

### ISSUE THREAD

**Issue by absywabsy** [TitansBane/Elysium#235]
> 0.23 - Wabbajack Build - fed371a6f1956ee74801c18be22a6d628c68bc0f
0.24 - Running in C:\Wabbajack\2.5.3.1
0.32 - Detected Windows Version: 10.0.19042.0
0.32 - System settings - (63.9GB RAM) (4GB Page), Display: 5120 x 1440 (9.8GB VRAM - VideoMemorySizeMb=10240)
0.32 - Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance.
0.34 - Getting new Wabbajack version list
0.42 - Steam: Found no Regex matches in Steam Config at c:/steam\config\config.vdf
0.42 - Steam: Found game Steamworks Common Redistributables (228980) at "C:\Steam\steamapps\common\Steamworks Shared"
0.42 - Steam: Found game Banished (242920) at "C:\Steam\steamapps\common\Banished"
0.42 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "C:\Steam\steamapps\common\Skyrim SE"
0.43 - Steam: Found game Steamworks Common Redistributables (228980) at "c:/steam\steamapps\common\Steamworks Shared"
0.43 - Steam: Found game Banished (242920) at "c:/steam\steamapps\common\Banished"
0.43 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "c:/steam\steamapps\common\Skyrim SE"
0.43 - GOG: RegistryKey HKEY_LOCAL_MACHINE\Software\WOW6432Node\GOG.com\Games\2060341617 does not have a value productID
0.43 - BethNet: Unable to open Registry Keys SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net and SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net
0.43 - EGS: ModSdkMetadataDir from Registry does not exist at C:/ProgramData/Epic/EpicGamesLauncher/Data/Manifests
0.43 - Origin: LocalContent directory at C:\ProgramData\Origin\LocalContent does not exist
0.76 - Wabbajack Version: 2.5.3.1
1.31 - Build server is alive
1.31 - File hash check (-42) d1287d0b69b09eea93cc0e3d697f034acaced2fe29e7348194b3877b3fe431ab
1.32 - Build server is alive
1.32 - File hash check (-42) d1287d0b69b09eea93cc0e3d697f034acaced2fe29e7348194b3877b3fe431ab
5.95 - Loading ModLists from GitHub
15.37 - Starting to install Elysium
15.38 - Cleaning VFS, this may take a bit of time
15.41 - Starting Installer Task
15.41 - Installation has Started
15.41 - File hash check (-42) d1287d0b69b09eea93cc0e3d697f034acaced2fe29e7348194b3877b3fe431ab
16.06 - Configuring Processor
16.07 - Install Folder: C:\Elysium
16.07 - Downloads Folder: C:\Elysium\downloads
16.07 - Game Folder: C:\Steam\steamapps\common\Skyrim SE
16.07 - Wabbajack Folder: C:\Wabbajack\2.5.3.1
16.07 - Drive watcher is starting. Will warn at 8GB and error at 4GB
16.07 - Starting Drive watcher on C:\ currently 1.3TB free out of 1.8TB
16.07 - Validating Game ESMs
16.08 - Creating Output Folders
16.73 - Optimizing ModList
16.73 - Optimizing ModList directives
18.68 - Looking for files to delete
18.75 - Cleaning empty folders
19.45 - Looking for unmodified files
19.81 - Updating ModList
19.81 - Optimized 241594 directives to 241594 required
19.87 - Hashing Archives
19.87 - Looking for files to hash
20.3 - Found 1561 total files, 1550 matching filesize
21.91 - Downloading Missing Archives
21.92 - Missing 1 archives
21.92 - Getting Nexus API Key, if a browser appears, please accept
21.93 - Loading server whitelist
22.09 - Loaded permissions for 592 servers and 266 Google Drive files
22.09 - File hash check (-42) d1287d0b69b09eea93cc0e3d697f034acaced2fe29e7348194b3877b3fe431ab
22.09 - Downloading TUDM - The Ultimate Dodge Mod v4 x64.rar
22.78 - Hashed download is incorrect
22.78 - Loading for alternative to U659DN1scQM=
22.95 - No alternative for U659DN1scQM= could be found
22.98 - Hashing Remaining Archives
22.98 - Looking for files to hash
23.27 - Found 1561 total files, 1550 matching filesize
23.66 - Unable to download TUDM - The Ultimate Dodge Mod v4 x64.rar (GoogleDriveDownloader+State|0B2VgBVA9jE6RTjJiYnRTTE9qRUE)
23.66 - Cannot continue, was unable to download one or more archives
23.66 - File hash check (-42) d1287d0b69b09eea93cc0e3d697f034acaced2fe29e7348194b3877b3fe431ab
23.68 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
24.22 - File hash check (-42) `d1287d0b69b09eea93cc0e3d697f034acaced2fe29e7348194b3877b3fe431ab

>

**Comment by motte49** [comment]
Go on discord there is a download link for the mod

**Comment by absywabsy** [comment]
> Go on discord there is a download link for the mod

Thanks
