### ISSUE TITLE
Can´t hash or download "Skyrim.ccc"

### ISSUE THREAD

**Issue by Dreizeh** [TitansBane/Elysium#236]
Hey everyone,
I haven't found a thread yet where this problem whas discused.
I keep getting this in the logs: 

0,77 - Wabbajack Version: 2.5.3.1
1,48 - Build server is alive
1,51 - Build server is alive
1,51 - File hash check (-42) db22add6912ac5c06e64713f8426c5d6ef4a113d8d3dd1a5271746ee2ab283f4
1,52 - File hash check (-42) db22add6912ac5c06e64713f8426c5d6ef4a113d8d3dd1a5271746ee2ab283f4
2,83 - Loading ModLists from GitHub
10,45 - Starting to install Elysium
10,47 - Cleaning VFS, this may take a bit of time
10,51 - Starting Installer Task
10,51 - Installation has Started
10,51 - File hash check (-42) db22add6912ac5c06e64713f8426c5d6ef4a113d8d3dd1a5271746ee2ab283f4
11,22 - Configuring Processor
11,23 - Install Folder: S:\Elysium
11,23 - Downloads Folder: S:\Games\Skyrim Elysium
11,23 - Game Folder: S:\Steam\steamapps\common\Skyrim SE
11,23 - Wabbajack Folder: S:\Wabbajack\2.5.3.1
11,24 - Drive watcher is starting. Will warn at 8GB and error at 4GB
11,24 - Starting Drive watcher on S:\ currently 276,2GB free out of 931,5GB
11,24 - Validating Game ESMs
11,25 - Creating Output Folders
11,48 - Optimizing ModList
11,48 - Optimizing ModList directives
15,59 - Looking for files to delete
15,6 - Cleaning empty folders
16,76 - Looking for unmodified files
17,43 - Updating ModList
17,43 - Optimized 241594 directives to 241594 required
17,55 - Hashing Archives
17,55 - Looking for files to hash
17,69 - Found 1686 total files, 1566 matching filesize
79,9 - Downloading Missing Archives
79,9 - Missing 1 archives
79,9 - Getting Nexus API Key, if a browser appears, please accept
79,92 - Loading server whitelist
80,06 - Loaded permissions for 593 servers and 266 Google Drive files
80,06 - File hash check (-42) db22add6912ac5c06e64713f8426c5d6ef4a113d8d3dd1a5271746ee2ab283f4
80,11 - Downloading Skyrim.ccc
80,12 - Hashed download is incorrect
80,12 - Loading for alternative to yLhCbCSfkuE=
80,21 - No alternative for yLhCbCSfkuE= could be found
80,32 - Hashing Remaining Archives
80,32 - Looking for files to hash
80,5 - Found 1687 total files, 1566 matching filesize
80,93 - Unable to download Skyrim.ccc (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|skyrim.ccc)
80,93 - Cannot continue, was unable to download one or more archives
80,93 - File hash check (-42) db22add6912ac5c06e64713f8426c5d6ef4a113d8d3dd1a5271746ee2ab283f4
80,95 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
81,23 - File hash check (-42) db22add6912ac5c06e64713f8426c5d6ef4a113d8d3dd1a5271746ee2ab283f4

**Comment by jonathonwood** [comment]
I've been getting that one along with failure on some other base game files:
631.82 - Unable to download Skyrim.ccc (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|skyrim.ccc)
631.82 - Unable to download SkyrimSE.exe (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|skyrimse.exe)
631.82 - Unable to download Data_Dawnguard.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\dawnguard.esm)
631.82 - Unable to download Data_Dragonborn.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\dragonborn.esm)
631.82 - Unable to download Data_HearthFires.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\hearthfires.esm)
631.82 - Unable to download Data_Update.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\update.esm)
631.82 - Unable to download Data_Skyrim - Animations.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - animations.bsa)
631.82 - Unable to download Data_Skyrim - Interface.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - interface.bsa)
631.82 - Unable to download Data_Skyrim - Meshes0.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - meshes0.bsa)
631.82 - Unable to download Data_Skyrim - Meshes1.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - meshes1.bsa)
631.82 - Unable to download Data_Skyrim - Misc.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - misc.bsa)
631.82 - Unable to download Data_Skyrim - Patch.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - patch.bsa)
631.82 - Unable to download Data_Skyrim - Shaders.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - shaders.bsa)
631.82 - Unable to download Data_Skyrim - Sounds.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - sounds.bsa)
631.82 - Unable to download Data_Skyrim.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim.esm)
631.82 - Unable to download Data_Skyrim - Textures3.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - textures3.bsa)
631.82 - Unable to download Data_Skyrim - Textures0.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - textures0.bsa)

I've verified Steam install, no help
I've manually copied these files from the steam Skyrim / Data folder, no help
I've manually copied them, then archived them to a rar file, no help.

Not sure how to proceed at this point. Really regretting my decision of "Hey let's update Elysium to see what new stuff has been added"

**Comment by jonathonwood** [comment]
Needed to run the "downgrader" in "Full Patcher" mode rather than "Best of Both Worlds" mode which is what I had been doing.
