### ISSUE TITLE
CTD after 20 mins of playing

### ISSUE THREAD

**Issue by Tphilly** [TitansBane/Elysium#237]
As the title ays really. I keep crashing to desktop after about 20 mins of playing. Tried multiple runs.

**Comment by lukeic** [comment]
It could be that your pagefile size is too small. Search for `D6DDDA` here for more info: https://www.nexusmods.com/skyrimspecialedition/articles/3031

https://www.thewindowsclub.com/increase-page-file-size-virtual-memory-windows - here's a link to increase it.
