### ISSUE TITLE
Unable to download xLODGen.84.7z

### ISSUE THREAD

**Issue by maksyudgil** [TitansBane/Elysium#239]
yo, I'm unable to download xLODGen.84.7z (MegaDownloader+State|https://mega.nz/file/dEwQnJRS#E-qpq29rVCBw3FxT3gTOjF_Z2zYkzR2CcWhQ5OAZcwg)
I know, that I can manually download it but this file is no longer exists, so can I please have a mirror or something? or you can suggest me something different?

**Comment by lotfidemian** [comment]
> yo, I'm unable to download xLODGen.84.7z (MegaDownloader+State|https://mega.nz/file/dEwQnJRS#E-qpq29rVCBw3FxT3gTOjF_Z2zYkzR2CcWhQ5OAZcwg) I know, that I can manually download it but this file is no longer exists, so can I please have a mirror or something? or you can suggest me something different?

Same here... I'm not able to download it from anywhere else and can't install Elysium at the moment. It seems we'll have to wait for now.

**Comment by LordPato** [comment]
I was almost done downloading the last package (basecoat) it went into maintenance mode. So I can't finish the installation :(

**Comment by FenriRaider** [comment]
Same for me and i try searching for an alternative download without find anything.

**Comment by maksyudgil** [comment]
found this file in Elysium discord channel 
https://cdn.discordapp.com/attachments/882031813676126298/916224122051235900/xLODGen.84.7z
I put it in the game folder and run the installer again

**Comment by FenriRaider** [comment]
> found this file in Elysium discord channel https://cdn.discordapp.com/attachments/882031813676126298/916224122051235900/xLODGen.84.7z I put it in the game folder and run the installer again and installation continued

THX SO MUCH!!!
