### ISSUE TITLE
Raindrops stuck on screen

### ISSUE THREAD

**Issue by destdanny** [TitansBane/Elysium#24]
Hi,

I have raindrops stuck on screen without there being any rain. I'm not sure what is causing this issue. I would like them to be removed but I don't find that option on ENB.

Image: https://i.imgur.com/fIOw46z.png

**Comment by Mogor** [comment]
Same issue, raindrop streaks on screen at all times and indoors, even when not raining. sorry no fix. I have tried disabling rain in ENB in-game and setting enable rain to false in enbseries in my SSE folder. Google results only show people trying to add this effect to their game; nobody else trying to just get rid of it. Thanks for reading!
