### ISSUE TITLE
Numerous issues relating to unavailable files and missing files.

### ISSUE THREAD

**Issue by FreeFragUK** [TitansBane/Elysium#243]
[Wabbajack.current.log](https://github.com/TitansBane/Elysium/files/7670029/Wabbajack.current.log)

Numerous issues relating to unavailable files and missing files.

**Comment by ronin9663** [comment]
Need to to downgrade game for the game files
https://github.com/TitansBane/Elysium/issues/234#issuecomment-977982411

The XLODGen.84 is available on discord

**Comment by FreeFragUK** [comment]
> Need to to downgrade game for the game files [#234 (comment)](https://github.com/TitansBane/Elysium/issues/234#issuecomment-977982411)
> 
> The XLODGen.84 is available on discord

Thanks Ronin, issue resolved. Apologies, should have spotted this info prior to raising the ticket.
