### ISSUE TITLE
Unable to finish download Elysium!!! FIX

### ISSUE THREAD

**Issue by RJORamos** [TitansBane/Elysium#244]
![11](https://user-images.githubusercontent.com/95770818/145256268-3e73526d-5cad-40ed-aaf6-fd7a5ee3f294.png)

**Comment by AlWoj45** [comment]
Same

**Comment by Chris-bay** [comment]
Elwaps, Elysium-Core and ReshadePreset can be downloaded by simply retrying/loggin in to mega. However the first Link is broken because there was a [new version of xLODGen](https://stepmodifications.org/forum/topic/13451-xlodgen-terrain-lod-beta-85-for-fnv-fo3-fo4-fo4vr-tes5-sse-tes5vr-enderal-enderalse/) released. Unfortunately there are no archives for older versions and Wabbajack does not want to procede without the correct one.

**Comment by ToxicGunner** [comment]
Yes same 4 mods aren't installing for me either. If we had links to the files we could install them and place them in the downloads file but I guess we can't do anything without xLODGen... This sucks...

**Comment by Chris-bay** [comment]
if you look into the log files you can extract the download links for each failed mod. 
Something like: `Unable to download xLODGen.84.7z (MegaDownloader+State|https://mega.nz/file/dEwQnJRS#E-qpq29rVCBw3FxT3gTOjF_Z2zYkzR2CcWhQ5OAZcwg)`

**Comment by SaintSolitude** [comment]
If you log into the Elysian support discord, all of the files are in pinned comments.

**Comment by AlWoj45** [comment]
I've manually downloaded Elysium - Dyndolod 3D Output files and installed them in downloads folder, but it is still not working with Wabbajack (even from disk)... I checked out the log and clicked on links for these files, it is always showing me up a "404 Not Found nginx/1.18.0 (Ubuntu)" page.

**Comment by lukeic** [comment]
You may be having the same issue as here: https://github.com/TitansBane/Elysium/issues/234
Try what the following comment suggests: https://github.com/TitansBane/Elysium/issues/234#issuecomment-977982411

If you don't want to follow the link, it says to downgrade the game using the following program:
https://www.nexusmods.com/skyrimspecialedition/mods/57618

**Comment by AlWoj45** [comment]
Thank you for help, it worked :)

**Comment by nomat19** [comment]
> You may be having the same issue as here: #234 Try what the following comment suggests: [#234 (comment)](https://github.com/TitansBane/Elysium/issues/234#issuecomment-977982411)
> 
> If you don't want to follow the link, it says to downgrade the game using the following program: https://www.nexusmods.com/skyrimspecialedition/mods/57618
> 
> Worked for me.

tried this, but the problem is that even with the downgrade the file is not available anymore

**Comment by dontpanic34** [comment]
Anyone can maybe share his download files ? i only miss 16 files ...

**Comment by dontpanic34** [comment]
> Thank you for help, it worked :)

Any chance your share your download files ? i miss 16 files to finish this instalation ...

**Comment by dontpanic34** [comment]
Before running the patcher you have to verifiy all your files on steam. Then it works
https://www.youtube.com/watch?v=fNOMpjh-0aQ

**Comment by RJORamos** [comment]
Guys, go to wabbajack's discord to the elysium support section and ask for help, many of the files are already pined there.
They will help you!!
