### ISSUE TITLE
Failed to install.

### ISSUE THREAD

**Issue by TheAngryFriend** [TitansBane/Elysium#254]
Wabbajack keeps failing to install the Modlist. I've attached the logfile
[Wabbajack.current.log](https://github.com/TitansBane/Elysium/files/7742597/Wabbajack.current.log)
.

**Comment by sciaba** [comment]
Same problem here. Given that nothing in Elysium was changed after the release of the AE, I suppose it's incompatible with it...

**Comment by MSWebber07** [comment]
Same exact files unable to download.
