### ISSUE TITLE
Low FPS and Long Wait Duration

### ISSUE THREAD

**Issue by mustafaulukaya** [TitansBane/Elysium#255]
I have experienced some bad FPS issues and extremely long load times.

CPU -> Intel i7 10750H
GPU -> NVIDIA GeForce RTX2060
The game is running off of a 7200RPM hard drive, but windows is installed to a separate SSD
32 GB 2933Mhz RAM

Load times for the main open world would sometimes take 4 minutes or so, and I'm seeing low FPS values depending on the area. Is this unusually low for the hardware I'm running it on, or is there something else up?

Also, can I downgrade any graphic settings?

**Comment by patata10010** [comment]
It's probably because your GPU is a not powerful enough...

You can try following this guide in order to boost your FPS: https://www.youtube.com/watch?v=UD6hj6N7ps8&t=209s
