### ISSUE TITLE
Any way to use FNIS with this overhaul?

### ISSUE THREAD

**Issue by Spacehonky** [TitansBane/Elysium#257]
I wanted to add some animations for flowing capes which requires the Fores animations tools, but the tools themselves appear to be locked into scanning and generating files for explicitly the "default" steam installation directory, thus running it via Elysium does not work.

Any suggestions?

**Comment by KuniXl** [comment]
Did you try Nemesis instead of FNIS?

**Comment by Spacehonky** [comment]
I hadn't considered that, thanks.
