### ISSUE TITLE
Wabbajack cannot install the last file. 'ruby ENB CV zangdar's Reshade presets' from mega download website.

### ISSUE THREAD

**Issue by ganshunter** [TitansBane/Elysium#26]
When I tried to manually install the Mega file it had encryption so it was not impossible to access it. Yes, I did try wabbajack extra 5 times to see if it can install by itself, but it failed all those times. So help?

**Comment by TheBiggestBoon** [comment]
I am having the same issue. I manually downloaded the file and put it in the downloads folder, but wabbajack doesnt seem to acknowledge its existence. I tried a few different times as well as deleting all the downloads and going in fresh, wont work.

**Comment by jeronimolina** [comment]
It is happening for me too, seems like a widespread issue.

**Comment by Soobrakay** [comment]
Go back to the modlist gallery and redownload the Elysium.wabbajack. Then run the install again. Mine is still going but it got past the stuck download for Rudy/Zang'dar and to the Installing Archives step.

https://discord.com/channels/605449136870916175/764605696808845353/804680994296037396

**Comment by ganshunter** [comment]
I tried again its works now!!

**Comment by jeronimolina** [comment]
I can confirm, working for me too!
