### ISSUE TITLE
The Whispering Door stage 10 bug (Cannot speak to Nelkir)

### ISSUE THREAD

**Issue by yolomancer** [TitansBane/Elysium#262]
After speaking to Jarl Balgruuf, the quest prompts you to speak to his child. However, Nelkir does not give you the options to talk to him, instead just giving standard one-liners like he usually does before the quest.

I would also like to add that Dawnguard initiation is not procing as well, which was an issue raised earlier.

**Comment by mathesoncd** [comment]
There's a mod in the list called Timing is Everything. It sets minimum levels and such for certain quests. You can modify it in the MCM. Should solve both of those
