### ISSUE TITLE
Not sure what to do its just failing

### ISSUE THREAD

**Issue by Anosein** [TitansBane/Elysium#266]
247.18 - Hashing Archives
247.19 - Looking for files to hash
247.35 - Found 1560 total files, 1550 matching filesize
247.59 - Downloading Missing Archives
247.59 - Missing 2 archives
247.59 - Getting Nexus API Key, if a browser appears, please accept
247.59 - Loading server whitelist
247.77 - Loaded permissions for 642 servers and 284 Google Drive files
247.77 - File hash check (-42) d4360d53270150156493fd2ee3e973f8555396c08e127a123f7bf12472a967fc
247.86 - Downloading xLODGen.84.7z
247.86 - Downloading Nemesis.Unlimited.Behavior.Engine.v0.84-beta.rar
247.88 - File hash check (-42) d4360d53270150156493fd2ee3e973f8555396c08e127a123f7bf12472a967fc
248.13 - Loading for alternative to uq8KT2b+f9A=
248.18 - Loading for alternative to Ypeg2MKgzlQ=
248.19 - No alternative for uq8KT2b+f9A= could be found
248.22 - No alternative for Ypeg2MKgzlQ= could be found
248.26 - Hashing Remaining Archives
248.26 - Looking for files to hash
248.4 - Found 1560 total files, 1550 matching filesize
248.61 - Unable to download xLODGen.84.7z (MegaDownloader+State|https://mega.nz/file/dEwQnJRS#E-qpq29rVCBw3FxT3gTOjF_Z2zYkzR2CcWhQ5OAZcwg)
248.61 - Unable to download Nemesis.Unlimited.Behavior.Engine.v0.84-beta.rar (HTTPDownloader+State|https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/releases/download/v0.84-beta/Nemesis.Unlimited.Behavior.Engine.v0.84-beta.rar)
248.61 - Cannot continue, was unable to download one or more archives
248.61 - File hash check (-42) d4360d53270150156493fd2ee3e973f8555396c08e127a123f7bf12472a967fc
248.61 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
248.71 - File hash check (-42) d4360d53270150156493fd2ee3e973f8555396c08e127a123f7bf12472a967fc
![caf8599c8f5303b990d1499b07751229](https://user-images.githubusercontent.com/97864100/149702722-18b19855-fa13-4464-a1d3-dc15843cf6c1.png)

**Comment by SDCaliber** [comment]
The Nemesis link has been taken down as the author is now uploading future versions on the nexus. 
Here: https://www.nexusmods.com/skyrimspecialedition/mods/60033
As for the LodGen file, you can find that in the pinned section of the Elysium Support page on the official Wabbajack Discord
or Here: https://mega.nz/file/sF5AWIoD#wi89GWmMsPoUEb7yHHjcfmfApaAAzFrUGru5UV3CsqM

**Comment by SDCaliber** [comment]
You just need to take the downloaded zip files and put them into the downloads folder where you are installing Elysium and relaunch wabba and hit download again and it should pick up fine.
