### ISSUE TITLE
Elysium Remastered - Dyndolod 3D Output.7z is failing to hash.

### ISSUE THREAD

**Issue by TheClock69** [TitansBane/Elysium#274]
Hi there,

Today, I have had a consistent issue with downloading the repository stated in the title. I am guessing this will be sorted in time, however I thought it worth mentioning, to potentially get it sorted, sooner.

The file/data will download - the progress bar will get all the way to the end in the next step, when hashing - and then I get a download failed notice.

Any support would be appreciated. I did try to download Elysium - Dyndolod 3D Output.7z from MEGA, but this, of course, is an old copy (I wondered if renaming it would help). I have also noticed the 'Elysium Remastered - Dyndolod 3D Output.7z' is in the downloads file at a respectable size of 5.51GB, as expected. It is strange to me that it would fail to hash. But, then again, I am still yet to even learn what 'hashing' is!

Thanks for your help.

I have enjoyed Skyrim Elysium in the past - and I am most excited to get on with it again, revamped!

All the best in life,

Jay/ TheClock69.

[Wabbajack 2022-02-28 17_07_48.log](https://github.com/TitansBane/Elysium-Remastered/files/8157676/Wabbajack.2022-02-28.17_07_48.log)
[Wabbajack 2022-02-28 18_12_57.log](https://github.com/TitansBane/Elysium-Remastered/files/8157677/Wabbajack.2022-02-28.18_12_57.log)
[Wabbajack 2022-02-28 22_21_28.log](https://github.com/TitansBane/Elysium-Remastered/files/8157678/Wabbajack.2022-02-28.22_21_28.log)
[Wabbajack.current.log](https://github.com/TitansBane/Elysium-Remastered/files/8157679/Wabbajack.current.log)

**Comment by TheClock69** [comment]
![image](https://user-images.githubusercontent.com/100643499/156402307-2da5b426-fe5f-49cd-be8e-5aac8f169533.png)

**Comment by Dreygor** [comment]
I am having a similiar issue, but Wabba just never finishes the download.  I have a Mega account with 1TB of transfer, so if it is there that shouldn't be the issue.  The file just doesn't Download all the way.

**Comment by Dreygor** [comment]
We are not going to get help on either here or the redit for this are we.

**Comment by Dreygor** [comment]
If we could just get the direct link to the Elysium Remastered DYNDOLOD 3D output.7zip file it would be helpful.  For some reason Wabba just will not download it all.  Left mine going for 10 hours now and it hasn't budged.

**Comment by TheClock69** [comment]
Bless you, Dreygor. 

I went to the discord server (wabbajack discord, and the elysium remastered support page, on there). Then - after trying all of the available and suggested methods (validating files, downloading with a vpn, network work around, downloading direct file from MEGA over 12 hours, etc.), I realised what must be done. 
So, I deleted skyrim - deleted all of the files on documents, and the steam games directory, I deleted all of the wabbajack downloads, and started again.
Freshly installing... Skyrim AE, CC content, then the wabbajack (WJ) elysium remastered WJ modlist. Low and behold... I needed more space - so made a total of 405GB of space... tried again... 'Installation Succesful'.

The discord server was helpful/ useful - but the fresh install was sound. 
I also got told to turn on the shader cache on the enblocal.ini file - a nice piece of advice.

Oh, and the game is pucka... well worth the fresh install and overcoming problems.

Good luck, Dreygor.

All the best,

Jay/ TheClock69

**Comment by Kallamamran** [comment]
I read nothing about Lovers Lab, VectorPlexus or Mega before deciding to try installing this so this has been something of a nightmare (Which is yet not ended 🤔)
...
0,18 - Wabbajack Build - 147bd70e9d7def3b412970763e3b0754c6cfb5de
0,18 - Running in D:\Wabbajack\2.5.3.9
0,19 - Detected Windows Version: 10.0.19044.0
0,19 - System settings - (15,9GB RAM) (4GB Page), Display: 3440 x 1440 (9,8GB VRAM - VideoMemorySizeMb=10240)
0,19 - Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance.
0,2 - Getting new Wabbajack version list
0,2 - Steam: Found no Regex matches in Steam Config at d:/steam\config\config.vdf
...
0,22 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "D:\Steam\steamapps\common\Skyrim Special Edition"
...
0,23 - BethNet: Unable to open Registry Keys SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net and SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net
0,26 - EpicGamesStore: Found game Second Extinction™ at "D:\Epic Games\SecondExtinction"
0,26 - Origin: Found no Ids and Paths in the MFST files
0,26 - Origin: Found no Ids for use with the Api
0,49 - Wabbajack Version: 2.5.3.9
0,89 - Build server is alive
0,89 - File hash check (-42) 6733a7ec524f3c2f0b60ba5bdf70e24c269d8865e884421ccec18427fc7e3c31
0,9 - Build server is alive
0,9 - File hash check (-42) 6733a7ec524f3c2f0b60ba5bdf70e24c269d8865e884421ccec18427fc7e3c31
3,62 - Loading ModLists from GitHub
4,1 - Error downloading modlist image Relics of Hyrule - GAT Edition
4,11 - Error downloading modlist image Relics of Hyrule - GAT Edition
4,54 - Error downloading modlist image OME(FT)
4,55 - Error downloading modlist image OME(FT)
20,72 - Starting to install Elysium Remastered
20,74 - Cleaning VFS, this may take a bit of time
20,77 - Starting Installer Task
20,77 - Installation has Started
20,78 - File hash check (-42) 6733a7ec524f3c2f0b60ba5bdf70e24c269d8865e884421ccec18427fc7e3c31
21,13 - Configuring Processor
21,13 - Install Folder: Z:\WabbajackInst
21,14 - Downloads Folder: Z:\WabbajackDL
21,14 - Game Folder: D:\Steam\steamapps\common\Skyrim Special Edition
21,14 - Wabbajack Folder: D:\Wabbajack\2.5.3.9
21,14 - Drive watcher is starting. Will warn at 8GB and error at 4GB
21,14 - Starting Drive watcher on Z:\ currently 1,4TB free out of 1,8TB
21,14 - Starting Drive watcher on D:\ currently 62,2GB free out of 465,6GB
21,14 - Validating Game ESMs
21,16 - Creating Output Folders
24,37 - Optimizing ModList
24,37 - Optimizing ModList directives
27,53 - Looking for files to delete
27,55 - Cleaning empty folders
28,28 - Looking for unmodified files
28,64 - Updating ModList
28,64 - Optimized 256661 directives to 256661 required
28,72 - Hashing Archives
28,72 - Looking for files to hash
28,73 - Found 37 total files, 13 matching filesize
28,75 - Downloading Missing Archives
28,76 - Missing 1873 archives
28,76 - Getting Nexus API Key, if a browser appears, please accept
29,07 - Logged into the nexus as kallamamran
29,07 - Nexus calls remaining: 10000 daily, 500 hourly
29,23 - Logged into the nexus as kallamamran
29,23 - Nexus calls remaining: 10000 daily, 500 hourly
29,23 - Loading server whitelist
29,31 - Loaded permissions for 652 servers and 292 Google Drive files
29,31 - File hash check (-42) 6733a7ec524f3c2f0b60ba5bdf70e24c269d8865e884421ccec18427fc7e3c31
29,33 - Encountered error, can't continue - System.Exception: File MegaDownloader+State|https://mega.nz/file/ccNCxbqA#zcsaLy1Yb3KhX_9UHv1feLkQqrzJGZARxTzATWBmNA4 failed validation
   at Wabbajack.Lib.AInstaller.DownloadArchives() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 226
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 144
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383

**Comment by TheClock69** [comment]
huh. oh, okay. 

So, what worked for me was the hard reset. Otherwise, please go to Wabbajack Discord - and seek the relative support page.
Then, I am sure they will ask you to validate your files through steam - 

Otherwise... restart!

Thanks, All the best,

TheClock69
