### ISSUE TITLE
CTD Cutting Trip Wire on Shroud Hearth Barrow

### ISSUE THREAD

**Issue by nihues** [TitansBane/Elysium#32]
After the room of skeletons archers, there is a door with a trip wire on the ground, every time I manual cut it, got CTD.
EDIT: 4th time reload to test and it auto cut this time (not me at least), no CTD

[Crash_2021_2_8_18-27-1.txt](https://github.com/TitansBane/Elysium/files/5946961/Crash_2021_2_8_18-27-1.txt)

**Comment by TitansBane** [comment]
Fixed for the update.
