### ISSUE TITLE
Creation Club - Once A Hunter Does Not Complete and Double Chest

### ISSUE THREAD

**Issue by Soobrakay** [TitansBane/Elysium#34]
**Profile:** Elysium - Creation Club
**Quest:** https://en.uesp.net/wiki/Skyrim:Once_A_Hunter

Found the book in the Falkreath Barracks -> Quest start.
Found Aesrael and killed him -> Search body stage.
Search body for Key -> Loot Armor Stage.

Two things:
* The chest with the armor is in the same spot as another chest and they are superimposed on each other in the game.
* Looting the armor does not end the quest. Using the `getstage` console command showed the quest at stage 70. Used `setstage` to put the quest at stage 80 to end the quest.

Unknown how much of this is Elysium vs Once A Hunter + The Unofficial Creation Club Patch.

**Comment by TitansBane** [comment]
Both issues fixed for v3.3.0.
