### ISSUE TITLE
Silver Sword needs steel ingot to upgrade

### ISSUE THREAD

**Issue by nihues** [TitansBane/Elysium#35]
I suppose should need silver ingot.

![Skyrim Special Edition25](https://user-images.githubusercontent.com/4883092/107992556-bf0e0f00-6fb7-11eb-902b-07231bb4c377.png)
![SkyrimSE 2021-02-15 17-59-43](https://user-images.githubusercontent.com/4883092/107992567-c208ff80-6fb7-11eb-8f34-4d7b4527761f.png)

**Comment by TitansBane** [comment]
CCOR intentionally changes this, so this isn't a bug.
