### ISSUE TITLE
Installation failed due to missing mods

### ISSUE THREAD

**Issue by lannudan** [TitansBane/Elysium#37]
The modpack currently fails to install because the following archives are hidden on the Nexus. 

- Dynamic Mountain Fogs - Cathedral Weathers
- Improved Atmosphere Mesh - Cathedral Edition
- Improved Cloud Mesh for Improved Atmosphere Mesh

They all appear to have been hidden on Feb 15th.

**Comment by TitansBane** [comment]
Elysium has updated, so redownload the list.

**Comment by lannudan** [comment]
Thanks. Thought I had the most recent version of the modlist.

**Comment by TitansBane** [comment]
Another version should be up soon.
