### ISSUE TITLE
Feature Request - Key Bindable Dual Wield Blocking

### ISSUE THREAD

**Issue by S-w-y-l-e-r** [TitansBane/Elysium#57]
Thank you for Elysium, it is amazing.  The difficulty and combat balance are excellent.  Far better than my individual efforts at modding Skyrim.

One feature I would love to see in addition is that of blocking while wielding a left handed spell/weapon.  This would improve spell sword, dual wield, and unarmed play styles in a (I believe) balanced manner.  Here are two mods to consider:

1.  With attack cancelling
https://www.nexusmods.com/skyrimspecialedition/mods/16334?tab=description

2.  Without attack cancelling
https://www.nexusmods.com/skyrimspecialedition/mods/18264?tab=description

Again, thank you for your consideration.  If this post is in the inappropriate location, I apologize.  I'm new to Skyrim modding and Github and I am trying to learn.  Thank you.

**Comment by TitansBane** [comment]
Dodging is already a thing for dual-wielding, so having blocking too would be something I would rather not add.
