### ISSUE TITLE
Can't use the pray and wash habilities

### ISSUE THREAD

**Issue by ferplus79** [TitansBane/Elysium#58]
Hi everybody

I've installed the Elysium modpack few days ago and is amazing. I only played unmoded Skirym in the Nintendo Swicht and this is another dimension.

Maybe is my fault, lack of experience or wharever but I can't use the option of pray, it seems to be inactive. The same happens whith the wash option. I speak about the habilities available in the magic menu.

I haven't found any information about this.

Many thanks.

**Comment by ferplus79** [comment]
I've solved it myself accidentally: just presing RB+LB at the same time.

Thank you, Ferplus.

**Comment by burnskyc** [comment]
> I've solved it myself accidentally: just presing RB+LB at the same time.
> 
> Thank you, Ferplus.

I'm having same trouble with mouse and keyboard. Do you know how it works with those controls?

**Comment by ferplus79** [comment]
I don't know wich is the corredpondant key to RB, but is the key asigned to use the shout powers. Previouslly you must select the pray or wharever hability in the magic menu.

**Comment by burnskyc** [comment]
Okay. thanks. I'll try that. I saw on discord that you can't pray with a weapon in either hand.
