### ISSUE TITLE
Unique Dragon Names Overwritten by Zim's Dragon Improvements

### ISSUE THREAD

**Issue by draconicfragor** [TitansBane/Elysium#65]
Zim's is overwritting the names of unique dragons added by other mods (LoTD's Herald of Akatosh for sure). Looks like Zim's has a formlist for unique dragons, so I'm going to try a custom patch that adds those NPCs to the list and seeing if it works. Granted, I'm not testing with a new save.

**Comment by TitansBane** [comment]
Fixed for version 3.4.2.
