### ISSUE TITLE
sh*t mod mesh improvement mod error 503

### ISSUE THREAD

**Issue by issoMEMO** [TitansBane/Elysium#69]
First time using the wabbajack method and tried installing elysium. One error appeared in the download process which was the mod mesh improvement from lovers lab that got a error 503 in it. Been waiting for a few hours now, but it doesn't seem to resolve itself. What to I do?
I tried following the installation instructions as well as I could, and am running the program as adm. Tried closing and running it again, but no changes on the 503 situation.

**Comment by reinlang** [comment]
Hello there! 
I have exactly the same issue with my Elysium installation. As far as I can tell, no solution was provided in this thread, yet it's already closed. Am I missing something? 
Here's a log Wabbajack formed for this error. Thank you for your support! 
[Wabbajack.current.log](https://github.com/TitansBane/Elysium/files/6347101/Wabbajack.current.log)
