### ISSUE TITLE
Dual wielding in slow motion after taking first "dual wielding 20% increase" perk in the one handed tree

### ISSUE THREAD

**Issue by simithommy** [TitansBane/Elysium#71]
The title says it all. Default Elysium installed by wabbajack with Ultrawide monitor mods as well, no bugs at all until I grabbed this perk at level 11. weapons work fine one-handed. They will even swing normally after unequipping and re-equipping until I actually try and hit a valid target, in which case they slow down and stay slowed down til unequipped and re-equipped again.

**Comment by simithommy** [comment]
So my weaponspeedmult is 1.2, til I hit somebody and it goes to .2. changing this in the console works until I try and power attack anybody, at which point it goes back down to .2. It has made my current character that I was really enjoying unplayable. Looking forward to a patch or news, thanks!

**Comment by MysteryumXarxes** [comment]
any news? because I've the same issue :(

**Comment by simithommy** [comment]
No updates, and I doubt it will be fixed without the modpack just being straight-up updated. I've found no fix which lasts longer than 5 seconds with console commands. I had to make a new character entirely cuz the one I had just didn't feel good anymore. Sorry bruddah.

**Comment by MysteryumXarxes** [comment]
I found a solution just yesterday and I wanted to update you. the problem lies in the "dual flurry" perk. From console, remove the perk totally (so both). My pg is back to attack with the right speed. Then personally, again from the console, I speeded it up by 0.2 sec to make it more dynamic. I hope you still have your old pg to verify that it works for you too. 

Ps. I hope I made myself understood, my english sucks lol

**Comment by deadcode0815** [comment]
Afaik this is a long time bug in skyrim which got never really true fixed. I also tried several console command with no luck.
Maybe this one helps https://www.nexusmods.com/skyrimspecialedition/mods/32859 - I have to make some tests this evening.

**Comment by simithommy** [comment]
Hey dude, I saved that save game so I could see about attempting to load it
up and see, though I am enjoying my current new character. I'll let you
know!

**Comment by TitansBane** [comment]
Fix for the next update.
