### ISSUE TITLE
Could Not Locate Skyrim Special Edition

### ISSUE THREAD

**Issue by Rhaevyn** [TitansBane/Elysium#73]
I've had a few stops already trying to install this, but restarting WJ pushed it on.  Not this time.  I've restarted WJ so many times now I've lost count.  I'm completely at a loss for words at this message.  I've already downloaded a few mod packs without issue, why this one suddenly can't see my game files is beyond me.  Hope someone has an answer.  Thank you.

**Comment by simithommy** [comment]
Bro, this question you'll get a better answer on the discord.

**Comment by Rhaevyn** [comment]
OK "sis" thanks! ;)
