### ISSUE TITLE
Missing patch for Alchemy & Food Adjustments and Survival Mode in Creation Club Profile

### ISSUE THREAD

**Issue by Skiamach** [TitansBane/Elysium#80]
There is a patch for Alchemy Potion and Food Adjustments and Survival Mode that should be included in the modlist for the CC profile. Here is the link to the patch: https://www.nexusmods.com/skyrimspecialedition/mods/48211. In survival mode without this patch eating does not reduce/remove hunger.

**Comment by TitansBane** [comment]
This is already patched into Elysium, so that patch is not needed at all.
