### ISSUE TITLE
Frequent CTD in 3.6.x

### ISSUE THREAD

**Issue by joe-woodhouse** [TitansBane/Elysium#83]
3.6.1, 3.6.2, 3.6.3 all introduce frequent CTDs on top of my previous totally stable 3.4.2. 

It's worse with each version. I maybe get a few minutes of play now under 3.6.3.

When 3.6.0 says it needs a totally new save game, is that true for everything else in the 3.6.x codeline?

If so then... I maybe need to stop updating Elysium and somehow go back to an older list because I had totally stable play and now it's as bad as if I tried to install 600+ mods manually. :(

May I suggest _not_ updating in ways that prevent continuing to be able to play? I can't restart a new game every update.

**Comment by joe-woodhouse** [comment]
I seem to have gotten past my issue by falling back to my last Full Save (fewer scripts) rather than relying on an autosave.

To be clear this is all on me for enthusiastically updating before reading the change log. I am merely sad to think that I cannot partake of the excellent work being done on Elysium and maintain my progress in game. Stability patches that don't change the mod list would be my preference.

**Comment by TitansBane** [comment]
Then don't update... *facepalm*

**Comment by joe-woodhouse** [comment]
Genuine question: who are your updates for, then, if they break games in progress, and why update at all if the updates can only be used by people who aren't currently using Elysium?

**Comment by TitansBane** [comment]
There is a warning not to update; if you can't read, that's not my problem.

**Comment by joe-woodhouse** [comment]
Wow.

Want to try answering the question? If updates break the ability to use Elysium, who are the updates for?
