### ISSUE TITLE
Issue in Bleak Falls Barrow

### ISSUE THREAD

**Issue by TheVozen** [TitansBane/Elysium#85]
Dear TitansBane, 

First of all, I would like to thank you for the awesome mod, I am very much enjoying it ! 

I however have a little issue with invisible textures in Bleak Falls Barrow, i can see through walls until i pass them 
which makes the underground extremely confusing. I took a little screenshot which i included here-under; 

![2021-04-27 (1)](https://user-images.githubusercontent.com/83308891/116298983-6a4bf900-a79d-11eb-8788-e13d19f0d02a.png)

I have absolutely no experience with modding, i tried deactivating dungeons mod from the left panel with no success. 

After scouring the web i found one individual on Living Skyrim 2 modpack who had a similar issue and the individual was recommended to upgrade the load order of the "Bleak Falls Barrow Revisited.esp" (https://github.com/ForgottenGlory/Living-Skyrim-2/issues/462). This means changing the order of plug-ins however I have absolutely no understanding of this and dont want to mess up the rest of the game. 

I am therefore curious whether or not you could help me out with this issue. 

Kind Regards, 

The Vozen

**Comment by TitansBane** [comment]
Which version of Elysium are you on? As this issue was fixed a long time ago.

**Comment by TheVozen** [comment]
I am using version 3.6.3, I downloaded it about a week ago from Wabbajack

**Comment by TitansBane** [comment]
Not getting this problem with Bleak Falls Barrow after testing in-game.
