### ISSUE TITLE
Performance Issues and Help with adding a perk point per level?

### ISSUE THREAD

**Issue by ttttannerr** [TitansBane/Elysium#86]
I have the following:
Ryzen 7 3700x
Tomahawk b550
Evga black 2070 super
16gb of ddr4 ram
I have my enb off and still have bad frame drops in the open areas but in cities I’m usually fine still a few frame drops here and there. Just need help with configuring best setting possible for my set up. I really enjoy the modpack.
As for the perk points how would I go about making it so that I can gain 2 perk points every level?
(I’ve updated everything today so I’ll see what goes on. Maybe I just needed an update. I’ll inform if need be.)

**Comment by TitansBane** [comment]
The performance will be improved in future updates.
