### ISSUE TITLE
System.Exception: Invalid file format C:\Wabbajack(SkyrimModding)\downloaded_mod_lists\elysium.wabbajack

### ISSUE THREAD

**Issue by MarkADuncan** [TitansBane/Elysium#87]
To make things short: I'm modding Skyrim SE for the first time, have worked through different issues that shouldn't be a problem anymore, and I'm stuck on the error shown in the title without the knowledge on how to get a fresh version of the modlist.

Any thoughts on how I could refresh my modlist file?

**Comment by TitansBane** [comment]
Rerun Wabbajack and click confirm to updating existing files.
