### ISSUE TITLE
Please consider replacing "Harvest Those Mammoth Skulls" with "Dynamic Things Alternative"

### ISSUE THREAD

**Issue by ave-** [TitansBane/Elysium#88]
[Dynamic Things Alternative](https://www.nexusmods.com/skyrimspecialedition/mods/49250) is much more versatile and supports more item activations. Also it uses already existing requirement (po3's Papyrus Extender v4.3.6 or above).

**Comment by TitansBane** [comment]
Already swap to it for the next update.
