### ISSUE TITLE
Unable to start VIGILANT mod

### ISSUE THREAD

**Issue by crkilg4z** [TitansBane/Elysium#9]
I have tried to begin the VIGLIANT mod questline multiple times on multiple characters, and every time I cannot even get the initial quest because EVERY npc with custom dialog that I have tried speaking to cannot be interacted with.  For example, upon entering Windpeak Inn, Altano repeatedly attempts to come up to me, then turns around and walks away and sits down somewhere, then repeats the same process over and over.  If I activate him to initiate dialog, he will headtrack look at me but nothing happens.  Same thing happens when I use the console to add and complete the quest stages to the point where I have to go and speak to  Thorondir, but same issue, he just looks at me when I activate him but no dialog will initiate.  I have searched everywhere online to see if this is a common issue and only found one reddit post where someone suggested to save beside him and reload, and that was the only comment.  I tried that to no avail, along with exiting and re-entering multiple times, waiting varying amounts of hours inside the inn and outside, as well as reinstalling both VIGILANT and the English Add-On but nothing seems to work.  I appreciate any help you can provide, and thank you for such an excellent modlist!

**Comment by TitansBane** [comment]
Starts at level 30 on this mod list; if you read the readme, you would already know it instead of reporting this non-existence issue.

**Comment by crkilg4z** [comment]
My apologies, I did read the readme but must have overlooked that part, thank you for the help
