### ISSUE TITLE
Unable to install: Dyndolod

### ISSUE THREAD

**Issue by Amkwras** [TitansBane/Elysium#91]
![image](https://user-images.githubusercontent.com/83874503/117543870-8c077480-b016-11eb-890d-c760e2865b2c.png)

I have been unable to install this modpack due to several broken downloads.
A the moment the only one that keeps failing is Dyndolod 3D. I have noticed that the last few updates have included this one being regenerated. Is this a known issue?

**Comment by Teron1545** [comment]
Greetings Mates, 

I´ve got the same issue here. 

I did all the Pre Installation Steps...

Don´t know how to fix this..

Can anyone Assist? 

Ben



![Fail Elysium 2](https://user-images.githubusercontent.com/84145936/118157778-4504ef00-b41b-11eb-9e19-c4214f2aaec1.JPG)
![Fail Elysium 3](https://user-images.githubusercontent.com/84145936/118157779-459d8580-b41b-11eb-8d44-a7ab9fd44e3e.JPG)

![Fail Elysium 1](https://user-images.githubusercontent.com/84145936/118157635-16871400-b41b-11eb-815f-965040ac86d1.JPG)

**Comment by MSaf19** [comment]
> Greetings Mates,
> 
> I´ve got the same issue here.
> 
> I did all the Pre Installation Steps...
> 
> Don´t know how to fix this..
> 
> Can anyone Assist?
> 
> Ben
> 
> ![Fail Elysium 2](https://user-images.githubusercontent.com/84145936/118157778-4504ef00-b41b-11eb-9e19-c4214f2aaec1.JPG)
> ![Fail Elysium 3](https://user-images.githubusercontent.com/84145936/118157779-459d8580-b41b-11eb-8d44-a7ab9fd44e3e.JPG)
> 
> ![Fail Elysium 1](https://user-images.githubusercontent.com/84145936/118157635-16871400-b41b-11eb-815f-965040ac86d1.JPG)

I have the same issue as you Ben. Did you ever find a fix for it?

**Comment by Teron1545** [comment]
@MSaf19 

No not yet... I´ll try to find some support via Discord now - I´ll Update.

**Comment by MSaf19** [comment]
> @MSaf19
> 
> No not yet... I´ll try to find some support via Discord now - I´ll Update.

Not sure if you solved it yet, but I solved mine my designating the download folder, as well as the installation folder (2 separated folders).

**Comment by happyduckss** [comment]
i have the same thing can some one help me :P
