### ISSUE TITLE
CTD near - Keld-Nar - related to Clockwork

### ISSUE THREAD

**Issue by medinaKrom1** [TitansBane/Elysium#97]
Hi,
near Keld-Nar, a bit to the west, where the first main road comes, is a giant camp  with a wounded Khajiit. 

See location picture:
[https://github.com/medinaKrom1/medinaKrom1/blob/3915d7916d10015f4a3396bf8ee9d9ccf85c35f7/Crash_2021_5_21_11-47-46.txt]
Crash log / NetFramework:
[https://github.com/medinaKrom1/medinaKrom1/blob/main/Crash_2021_5_21_11-47-46.txt]

The CTD in this area is not exactly reproducible each time, but happens just by walking through often.
After some research, I found out a relation between Keld-Nar and Clockwork which is causing possible CTD' s, 
but I can't simply remove one of these modes without handle the references in other esp' s.

Can you provide a solution for this problem?

**Thank you so much for this awesome modlist, provided to the comunity.**

testet modlist Version: 1.90

**Comment by TitansBane** [comment]
Version 1.9.0 had that issue which is now fixed.
