### ISSUE TITLE
.NET Script Framework Causing Immediate Crash

### ISSUE THREAD

**Issue by oomcommander** [TitansBane/Elysium#98]
So I had raised an issue before, with a very generic "it's crashing on startup" [issue](https://github.com/TitansBane/Elysium/issues/92). That was a couple weeks ago, and I gave up, skyrim shredded everything, deleted Wabbajack and all the related Elysium folders. I started again from scratch today and still got the same ambiguous crash.

I get that it isn't a lot to go on, so I'm hoping I've narrowed it down. I duplicated the Elysium profile in MO2 and started deactivating every mod in a category until the crash stopped. The good news is that I may have found found the problem. The bad news is that it's in the ESSENTIAL MODS category, and it's the .NET Script Framework. With it loaded, I get the crash in the issue linked above, without it, the game does start, but doesn't really do anything. Understandable.

I'm raising this here to see if you guys would like me to provide some kind of logs (I don't know where they would be) or other info. If it's really not something you can help with, that's also fine. Thanks.

**Comment by TitansBane** [comment]
Disable your Antivirus software like Webroot, for example; else your Skyrim won't launch with .NET Script Framework enable.

**Comment by oomcommander** [comment]
Yeah, I'm a bit of an absolute mongoloid. Thanks.
